import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

/// UI preferences: locale (zh-CN / en-US), the native task-list switch and
/// the notification switches (master + per channel).
class UiSettings extends ChangeNotifier {
  static const _localeKey = 'zremote_ui_locale';
  static const _nativeListKey = 'zremote_native_list';
  static const _notifyKey = 'zremote_notify';
  static const _notifyTasksKey = 'zremote_notify_tasks';
  static const _notifyOffPeakKey = 'zremote_notify_offpeak';
  static const _notifyAutoKey = 'zremote_notify_auto';

  String locale = 'zh-CN';
  bool nativeListEnabled = true;
  bool notificationsEnabled = true;
  bool notifyTasksEnabled = true;
  bool notifyOffPeakEnabled = true;
  bool notifyAutoEnabled = true;

  Future<void> load() async {
    final prefs = await SharedPreferences.getInstance();
    locale = prefs.getString(_localeKey) ?? 'zh-CN';
    nativeListEnabled = prefs.getBool(_nativeListKey) ?? true;
    notificationsEnabled = prefs.getBool(_notifyKey) ?? true;
    notifyTasksEnabled = prefs.getBool(_notifyTasksKey) ?? true;
    notifyOffPeakEnabled = prefs.getBool(_notifyOffPeakKey) ?? true;
    notifyAutoEnabled = prefs.getBool(_notifyAutoKey) ?? true;
    notifyListeners();
  }

  Future<void> setLocale(String value) async {
    locale = value;
    notifyListeners();
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString(_localeKey, value);
  }

  Future<void> setNativeListEnabled(bool value) async {
    nativeListEnabled = value;
    notifyListeners();
    final prefs = await SharedPreferences.getInstance();
    await prefs.setBool(_nativeListKey, value);
  }

  Future<void> setNotificationsEnabled(bool value) async {
    notificationsEnabled = value;
    notifyListeners();
    final prefs = await SharedPreferences.getInstance();
    await prefs.setBool(_notifyKey, value);
  }

  Future<void> setNotifyTasksEnabled(bool value) async {
    notifyTasksEnabled = value;
    notifyListeners();
    final prefs = await SharedPreferences.getInstance();
    await prefs.setBool(_notifyTasksKey, value);
  }

  Future<void> setNotifyOffPeakEnabled(bool value) async {
    notifyOffPeakEnabled = value;
    notifyListeners();
    final prefs = await SharedPreferences.getInstance();
    await prefs.setBool(_notifyOffPeakKey, value);
  }

  Future<void> setNotifyAutoEnabled(bool value) async {
    notifyAutoEnabled = value;
    notifyListeners();
    final prefs = await SharedPreferences.getInstance();
    await prefs.setBool(_notifyAutoKey, value);
  }
}

class UiSettingsProvider extends InheritedWidget {
  final UiSettings settings;

  const UiSettingsProvider({
    super.key,
    required this.settings,
    required super.child,
  });

  static UiSettings? of(BuildContext context) => context
      .dependOnInheritedWidgetOfExactType<UiSettingsProvider>()
      ?.settings;

  @override
  bool updateShouldNotify(UiSettingsProvider oldWidget) =>
      settings != oldWidget.settings;
}

/// Lightweight i18n lookup (single-file table scheme).
String tr(BuildContext context, String key) =>
    trLocale(UiSettingsProvider.of(context)?.locale ?? 'zh-CN', key);

/// Context-free lookup for surfaces without a BuildContext (push
/// notifications render outside the widget tree).
String trLocale(String locale, String key) {
  final table = locale.startsWith('en') ? _en : _zh;
  return table[key] ?? _zh[key] ?? key;
}

/// [tr] with positional substitution: `$0`, `$1`, ... in the template are
/// replaced by [args] in order.
String trP(BuildContext context, String key, List<String> args) {
  var out = tr(context, key);
  for (var i = 0; i < args.length; i++) {
    out = out.replaceAll('\$$i', args[i]);
  }
  return out;
}

/// Relative-time formatting using the 'time.*' table keys.
String relativeTime(BuildContext context, int ms) {
  final diff =
      DateTime.now().difference(DateTime.fromMillisecondsSinceEpoch(ms));
  if (diff.inMinutes < 1) return tr(context, 'time.justNow');
  if (diff.inHours < 1) {
    return trP(context, 'time.minutesAgo', ['${diff.inMinutes}']);
  }
  if (diff.inDays < 1) {
    return trP(context, 'time.hoursAgo', ['${diff.inHours}']);
  }
  if (diff.inDays < 30) {
    return trP(context, 'time.daysAgo', ['${diff.inDays}']);
  }
  return DateTime.fromMillisecondsSinceEpoch(ms)
      .toLocal()
      .toString()
      .substring(0, 10);
}

/// Official list/sidebar compact relative time: `27分` / `1小时` / `13天`.
String relativeTimeShort(BuildContext context, int ms) {
  final diff =
      DateTime.now().difference(DateTime.fromMillisecondsSinceEpoch(ms));
  if (diff.inMinutes < 1) return tr(context, 'time.short.justNow');
  if (diff.inHours < 1) {
    return trP(context, 'time.short.minutes', ['${diff.inMinutes}']);
  }
  if (diff.inDays < 1) {
    return trP(context, 'time.short.hours', ['${diff.inHours}']);
  }
  if (diff.inDays < 30) {
    return trP(context, 'time.short.days', ['${diff.inDays}']);
  }
  return DateTime.fromMillisecondsSinceEpoch(ms)
      .toLocal()
      .toString()
      .substring(0, 10);
}

const _zh = {
  'app.title': 'ZRemote',
  'devices.empty.title': '还没有设备',
  'devices.empty.body': '在桌面 ZCode 中打开「远程控制」，\n扫码或粘贴链接即可添加设备',
  'devices.add': '添加设备',
  'devices.add.scan': '扫码添加',
  'devices.add.scanHint': '对准桌面端 ZCode 远程控制二维码',
  'devices.add.paste': '粘贴链接添加',
  'devices.add.pasteHint': '粘贴远程控制 URL',
  'devices.add.pasteTitle': '粘贴链接添加',
  'devices.add.pasteHint2': 'https://zcode.z.ai/remote/v4?sid=...&hash=...&t=...',
  'devices.add.cancel': '取消',
  'devices.add.confirm': '添加',
  'devices.add.savedUnparsed': 'URL 无法解析，但仍已保存',
  'devices.scan.title': '扫码添加设备',
  'devices.scan.fromGallery': '从相册选择二维码图片',
  'devices.scan.cameraError': '相机不可用: \$0\n可改用右上角从图片识别',
  'devices.scan.cameraInitFailed': '相机初始化失败',
  'devices.scan.decodeFailed': '未能从图片中识别二维码',
  'devices.scan.decodeError': '图片识别失败: \$0',
  'devices.scan.hint': '对准桌面端 ZCode 远程控制二维码，或从相册选择二维码截图',
  'devices.lastUsed': '上次使用 \$0',
  'devices.neverUsed': '从未使用',
  'devices.menu.rename': '重命名',
  'devices.menu.pin': '置顶',
  'devices.menu.unpin': '取消置顶',
  'devices.menu.web': '网页版打开',
  'devices.menu.browser': '在浏览器中打开',
  'devices.menu.copy': '复制链接',
  'devices.menu.delete': '删除',
  'devices.clipboard.offer': '剪贴板里有一条远程控制链接，要添加吗？',
  'devices.clipboard.add': '添加',
  'devices.menu.export': '导出设备备份',
  'devices.menu.import': '导入设备备份',
  'devices.rename.title': '重命名设备',
  'devices.rename.hint': '设备名称',
  'devices.rename.save': '保存',
  'devices.delete.title': '删除设备',
  'devices.delete.body': '确定要删除「\$0」吗？',
  'devices.delete.confirm': '删除',
  'devices.copy.done': '链接已复制',
  'devices.export.done': '已复制设备备份 JSON 到剪贴板',
  'devices.import.title': '导入设备',
  'devices.import.hint': '粘贴设备备份 JSON',
  'devices.import.confirm': '导入',
  'devices.import.done': '已导入 \$0 台设备',
  'devices.import.invalid': '备份格式无效',
  'devices.unnamed': '未命名设备',
  'status.online': '在线',
  'status.connecting': '连接中…',
  'status.offline': '离线',
  'status.error': '原生列表不可用，请用网页版',
  'status.kicked': '已被其他终端接管',
  'status.tasksRunning': '\$0 个任务运行中',
  'time.justNow': '刚刚',
  'time.minutesAgo': '\$0 分钟前',
  'time.hoursAgo': '\$0 小时前',
  'time.daysAgo': '\$0 天前',
  'time.short.justNow': '刚刚',
  'time.short.minutes': '\$0分',
  'time.short.hours': '\$0小时',
  'time.short.days': '\$0天',
  'tasks.title': '任务',
  'tasks.empty': '暂无任务',
  'tasks.loading': '正在获取任务列表…',
  'tasks.fallback.title': '原生列表不可用',
  'tasks.fallback.body': '协议连接未就绪，可先用网页版操作此设备。',
  'tasks.openWeb': '网页版打开',
  'tasks.retry': '重试',
  'tasks.stop': '停止',
  'tasks.pause': '暂停',
  'tasks.resume': '恢复',
  'tasks.opFailed': '操作失败: \$0',
  'tasks.untitled': '未命名任务',
  'tasks.workspaces': '工作区',
  'tasks.pickWorkspace': '选择工作区',
  'tasks.noWorkspaces.title': '桌面端没有打开的工作区',
  'tasks.noWorkspaces.body': '请先在桌面 ZCode 中打开一个项目，再回到这里重试',
  'tasks.deepLinking': '正在直达任务…',
  'phase.running': '运行中',
  'phase.prewarming': '预热中',
  'phase.completedSuccess': '已完成',
  'phase.completedInterrupted': '已中断',
  'phase.error': '出错',
  'phase.draft': '草稿',
  'phase.paused': '已暂停',
  // ---- chat (native conversation) ----
  'chat.appBar': '任务会话',
  'chat.copy': '复制',
  'chat.copied': '已复制',
  'chat.expand': '展开',
  'chat.collapse': '收起',
  'chat.empty': '暂无消息',
  'chat.draftHint': '输入消息开始新任务',
  'chat.noSession': '尚无会话',
  'chat.noOlder': '没有更早的消息了',
  'chat.loadOlder': '加载更早消息',
  'chat.loadOlder.failed': '加载失败: \$0',
  'chat.subscribe.failed': '订阅失败: \$0',
  'chat.reconnecting': '连接已断开，正在自动重连…',
  'chat.kicked.title': '已被其他设备接管',
  'chat.kicked.body': '同一任务同时只允许一个终端连接，可在其他设备退出后重新连接。',
  'chat.kicked.reconnect': '重新连接',
  'chat.creating': '正在创建会话（首次可能需要预热）…',
  'chat.send.failed': '发送失败: \$0',
  'chat.op.failed': '操作失败: \$0',
  'chat.compact.failed': '压缩失败',
  'chat.goal.pauseFailed': '暂停目标失败',
  'chat.goal.resumeFailed': '恢复目标失败',
  'chat.held.title': '有排队中的消息',
  'chat.held.body': '立即发送将清空排队消息并插队执行',
  'chat.held.keep': '排队发送',
  'chat.held.clear': '立即发送',
  'chat.reasoning': '思考过程',
  'chat.reasoning.thinking': '思考中…',
  'chat.turn.worked': '已工作 \$0',
  'chat.time.secOnly': '\$0 秒',
  'chat.time.minSec': '\$0 分 \$1 秒',
  'chat.files.changed': '\$0 个文件已更改',
  'chat.files.undo': '撤销',
  'chat.subagent': '子代理 · \$0',
  'chat.bgWorks': '后台任务 \$0 个运行中: \$1',
  'chat.tool.input': '输入',
  'chat.tool.output': '输出',
  'chat.tool.error': '错误',
  'chat.tool.wrote': '已写入 \$0',
  'chat.tool.terminal': '终端',
  'chat.tool.explore': '探索',
  'chat.tool.exploreN': '探索 · \$0 文件',
  'chat.marker.compact': '压缩上下文 · \$0\$1',
  'chat.marker.tokens': ' · \$0→\$1 tokens',
  'chat.marker.forkNotice': '从会话分叉而来',
  'chat.marker.forkCreated': '已创建分叉会话',
  'chat.marker.modelChange': '模型切换 \$0 → \$1',
  'chat.marker.goalSet': '设定目标: \$0',
  'chat.marker.goalVerify': '目标验证 第\$0轮 · \$1',
  'chat.marker.retryNotice': '自动重试 第\$0次 (\$1)',
  'chat.marker.checkpointRestored': '已恢复检查点',
  'chat.queue.count': '排队消息 \$0',
  'chat.queue.autoOn': '自动发送: 开',
  'chat.queue.autoOff': '自动发送: 关',
  'chat.queue.sendNow': '立即发送',
  'chat.queue.edit': '编辑',
  'chat.queue.edit.title': '编辑排队消息',
  'chat.queue.delete.title': '删除排队消息？',
  'chat.interact.permission': '权限请求 · \$0',
  'chat.interact.waiting': '等待你的输入',
  'chat.interact.hint': '输入回复…',
  'chat.interact.allowOnce': '允许一次',
  'chat.interact.allowAlways': '总是允许',
  'chat.interact.deny': '拒绝',
  'chat.interact.custom': '自定义',
  'chat.interact.pick': '选择',
  'chat.interact.submit': '提交',
  'chat.mode.build': '构建',
  'chat.mode.edit': '编辑',
  'chat.mode.plan': '规划',
  'chat.mode.yolo': '自动',
  'chat.followup.queue': '排队',
  'chat.followup.guide': '引导',
  'chat.sheet.title': '模型与模式',
  'chat.sheet.draftTitle': '新任务 · 模型与模式',
  'chat.sheet.currentModel': '当前模型: \$0',
  'chat.sheet.thought': '思考等级',
  'chat.sheet.mode': '协作模式',
  'chat.sheet.followup': '后续消息',
  'chat.sheet.other': '其他配置',
  'chat.sheet.rejected': '被拒绝: \$0',
  'chat.usage.context': '上下文',
  'chat.usage.input': '累计输入',
  'chat.usage.output': '累计输出',
  'chat.usage.cacheRead': '缓存读取',
  'chat.usage.cacheWrite': '缓存写入',
  'chat.json.empty': '（无数据）',
  'chat.slash.empty': '没有匹配的命令',
  'chat.skills.title': '选择 Skills',
  'chat.skills.empty': '没有可用的 Skills',
  'chat.input.hint': '提出后续修改要求',
  'chat.input.attach': '添加上下文',
  'chat.attach.pickFailed': '选择文件失败: \$0',
  'chat.attach.uploading': '正在上传附件…',
  'chat.attach.loadFailed': '[图片加载失败] \$0',
  'chat.more': '更多',
  'chat.more.rename': '重命名任务',
  'chat.more.rename.hint': '任务名称',
  'chat.more.rename.save': '保存',
  'chat.more.pin': '置顶',
  'chat.more.archive': '归档',
  'chat.more.unread': '标记未读',
  'chat.more.copyPath': '复制路径',
  'chat.more.copyId': '复制任务 ID',
  'chat.more.copyLink': '复制任务链接',
  'chat.more.linkCopied': '任务链接已复制',
  'chat.more.idCopied': '任务 ID 已复制',
  'chat.more.pathCopied': '路径已复制',
  'chat.more.noPath': '没有可用的工作区路径',
  'chat.more.noLink': '没有可用的任务链接',
  'chat.more.compact': '压缩上下文',
  'chat.more.usage': '用量统计',
  'chat.more.plans': '计划',
  'chat.plans': '计划',
  'chat.plans.failed': '获取计划失败: \$0',
  'chat.action.editResend': '编辑并重发',
  'chat.action.edit.title': '编辑消息',
  'chat.action.edit.failed': '编辑失败: \$0',
  'chat.action.retry': '重试本轮',
  'chat.action.retry.failed': '重试失败',
  'chat.action.fork': '分叉对话',
  'chat.action.fork.failed': '分叉失败',
  'chat.action.rewind': '回滚文件到此',
  'chat.action.rewind.title': '回滚文件？',
  'chat.action.rewind.body': '将把此消息之后产生的文件变更回滚，对话保留',
  'chat.action.rewind.confirm': '回滚',
  'chat.action.rewind.failed': '回滚失败',
  'chat.action.fileChanges': '查看文件变更',
  'chat.action.fileChanges.failed': '获取失败: \$0',
  'chat.diff.truncated': '…（diff 过长已截断）',
  // ---- task list (official mobile layout) ----
  'tasks.sectionTitle': '当前设备上的工作区和任务',
  'tasks.stats': '\$0 个工作区 · \$1 个任务',
  'tasks.collapseAll': '收起全部',
  'tasks.expandAll': '展开全部',
  'tasks.tidy': '整理',
  'tasks.updatedAt': '更新于 \$0',
  'tasks.taskCount': '\$0 个任务',
  'tasks.local': '本地',
  'tasks.new': '新建任务',
  'tasks.banner.nativeOff': '原生列表未启用，可在设置中开启',
  'tasks.banner.kicked': '其他终端占用了此设备连接，可等待其退出后重试',
  'tasks.banner.connecting': '正在连接桌面端…',
  'tasks.banner.onlineTitle': 'ZCode 远程控制',
  'tasks.banner.onlineSubtitle': '已连接到当前桌面窗口',
  'tasks.banner.onlineDesc': '本次连接可以查看当前设备上已打开的项目、任务和会话；二维码失效后需要回到桌面端重新连接。',
  'tasks.paneHint': '选择左侧任务查看会话',
  'tasks.commandSearch': '搜索并执行当前工作区可用的命令',
  'tasks.commandSearch.empty': '没有匹配的命令',
  'tasks.pinned': '已置顶',
  'tasks.projects': '项目',
  'tasks.search': '搜索',
  'tasks.sidebar.new': '新建任务',
  'remote.error.title': '无法连接到桌面设备',
  'remote.error.hint': '请确认桌面 ZCode 已打开且网络可用',
  'remote.reload': '重新加载',
  'settings.title': '设置',
  'settings.appearance': '外观',
  'settings.theme': '主题',
  'settings.theme.dark': '深色',
  'settings.theme.light': '浅色',
  'settings.theme.system': '跟随系统',
  'settings.general': '通用',
  'settings.language': '语言',
  'settings.language.zh': '中文',
  'settings.language.en': 'English',
  'settings.nativeList': '原生任务列表',
  'settings.nativeListHint': '原生显示设备在线状态与任务列表；关闭后仅用网页版',
  'settings.data': '数据',
  'settings.usageStats': '使用统计',
  'settings.usageStatsHint': '仅保存在本机',
  'settings.about': '关于 ZRemote',
  'about.version': '版本',
  'about.github': 'GitHub 仓库',
  'about.licenses': '开源许可',
  'about.privacy': '隐私政策',
  'about.tos': '服务条款',
  'about.disclaimer': 'ZRemote 是非官方的社区客户端，与 Zhipu AI 及 ZCode 无关联。',
  'usage.title': '使用统计',
  'usage.summary.devices': '设备数',
  'usage.summary.opens': '累计打开',
  'usage.perDevice': '按设备',
  'usage.opens': '\$0 次',
  'usage.addedAt': '添加于 \$0',
  'usage.neverUsed': '从未使用',
  'tasks.menu.usage': '用量',
  'tasks.menu.providers': '模型供应商',
  'usageRpc.title': '用量',
  'usageRpc.loadFailed': '加载失败: \$0',
  'usageRpc.remaining': '剩余额度',
  'usageRpc.remainingDetail': '剩余 \$0% · 重置时间 \$1',
  'usageRpc.limits': '配额限制',
  'usageRpc.subscription': '订阅',
  'usageRpc.product': '产品',
  'usageRpc.billing': '计费周期',
  'usageRpc.renew': '续费时间',
  'usageRpc.expire': '到期时间',
  'usageRpc.used': '用量 \$0',
  'usageRpc.left': '剩余 \$0',
  'usageRpc.resetAt': '重置 \$0',
  'providers.title': '模型供应商',
  'providers.add': '添加',
  'providers.addTitle': '添加模型供应商',
  'providers.name': '名称',
  'providers.apiFormat': 'API 格式',
  'providers.apiKey': 'API Key（可选）',
  'providers.models': '模型 ID（逗号分隔）',
  'providers.modelsCount': '\$0 个模型',
  'providers.disabled': '停用: \$0',
  'providers.loadFailed': '加载失败: \$0',
  'providers.toggleFailed': '切换失败: \$0',
  'providers.deleteFailed': '删除失败: \$0',
  'providers.addFailed': '添加失败: \$0',
  'providers.added': '已添加供应商',
  'providers.deleteTitle': '删除模型供应商？',
  'providers.deleteBody': '将删除「\$0」',
  'sched.menu': '定时与自动化',
  'sched.title': '定时与自动化',
  'sched.section.server': '设备自动化',
  'sched.section.local': '本地定时发送',
  'sched.openAuto': '管理设备自动化',
  'sched.add': '新建定时消息',
  'sched.empty': '暂无定时消息',
  'sched.noDevices': '请先添加可用设备',
  'sched.created': '已创建定时消息',
  'sched.device': '设备',
  'sched.message': '消息内容',
  'sched.time': '发送时间',
  'sched.pending': '待发送',
  'sched.sent': '已发送',
  'sched.failed': '失败',
  'sched.hint': '到点时需保持 App 在前台，且开启「原生任务列表」',
  'tasks.menu.automations': '自动化',
  'auto.title': '自动化',
  'auto.subtitle': '由桌面端定时调度，无需 App 在线',
  'auto.add': '新建自动化',
  'auto.edit': '编辑自动化',
  'auto.empty': '暂无自动化',
  'auto.loading': '正在获取自动化列表…',
  'auto.loadFailed': '加载失败: \$0',
  'auto.unavailable.title': '设备自动化不可用',
  'auto.unavailable.body':
      '设备离线或协议握手未完成。可先用「本地定时发送」兜底，设备上线后再来管理。',
  'auto.opFailed': '操作失败: \$0',
  'auto.created': '已创建自动化',
  'auto.saved': '已保存',
  'auto.deleted': '已删除',
  'auto.delete.title': '删除自动化？',
  'auto.delete.body': '将删除「\$0」',
  'auto.enabled': '已启用',
  'auto.disabled': '已停用',
  'auto.name': '标题',
  'auto.prompt': '指令',
  'auto.hint': '由桌面端调度进程定时触发，无需 App 在线',
  'auto.trigger': '触发规则',
  'auto.trigger.cron': 'Cron',
  'auto.trigger.interval': '间隔重复',
  'auto.trigger.oneShot': '一次性延迟',
  'auto.cronExpr': 'Cron 表达式',
  'auto.cronHint': '5 段式，如 0 9 * * 1-5 表示工作日每天 9 点',
  'auto.interval': '间隔',
  'auto.intervalUnit.label': '单位',
  'auto.intervalUnit.minute': '分钟',
  'auto.intervalUnit.hour': '小时',
  'auto.intervalUnit.day': '天',
  'auto.intervalUnit.week': '周',
  'auto.intervalUnit.month': '月',
  'auto.intervalUnit.year': '年',
  'auto.recurring': '无限重复',
  'auto.maxRuns': '最大运行次数',
  'auto.maxRunsN': '最多 \$0 次',
  'auto.delayMinutes': '延迟分钟数',
  'auto.delayHint': '从创建时起延迟执行，最长 1 年',
  'auto.model': '模型（可选）',
  'auto.mode': '模式（可选）',
  'auto.mode.default': '默认',
  'auto.thoughtLevel': '思考等级（可选）',
  'auto.targetTask': '绑定任务 ID（可选）',
  'auto.advanced': '更多选项',
  'auto.cronAt': '按 Cron \$0',
  'auto.every': '每 \$0 \$1',
  'auto.once': '一次性 · \$0后',
  'auto.minutes': '\$0 分钟',
  'auto.hours': '\$0 小时',
  'auto.days': '\$0 天',
  'auto.lastRun': '上次触发 \$0',
  'auto.err.title': '请填写标题',
  'auto.err.prompt': '请填写指令',
  'auto.err.cron': '请填写 Cron 表达式',
  'auto.err.interval': '间隔需为正整数',
  'auto.err.delay': '延迟需在 1 分钟到 1 年之间',
  'tasks.menu.offPeak': '闲时任务',
  'op.title': '闲时任务',
  'op.subtitle': '算力富余时段免费执行 · Coding Plan',
  'op.hint': '提交后排队，在算力富余时段免费执行；需要 Coding Plan 订阅',
  'op.add': '新建闲时任务',
  'op.submit': '提交',
  'op.empty': '暂无闲时任务',
  'op.loading': '正在获取闲时任务…',
  'op.loadFailed': '加载失败: \$0',
  'op.unavailable.title': '闲时任务不可用',
  'op.unavailable.body': '设备离线或协议握手未完成，稍后再试。',
  'op.name': '标题',
  'op.prompt': '指令',
  'op.model': '模型（可选）',
  'op.earliestAt': '最早可用时间（可选）',
  'op.earliest.any': '不限，排队后尽快',
  'op.keepAwake': '保持唤醒',
  'op.keepAwakeHint': '保持与设备的连接，以便及时收到结果',
  'op.permission': '权限模式',
  'op.permission.build': 'build',
  'op.permission.plan': 'plan',
  'op.permission.yolo': 'yolo',
  'op.tpl.ci.title': 'CI flaky 报告',
  'op.tpl.ci.prompt': '分析最近的 CI 失败，找出 flaky 测试并输出报告',
  'op.tpl.docs.title': '文档同步检查',
  'op.tpl.docs.prompt': '检查最近代码变更涉及的文档是否需要同步更新，列出过期条目',
  'op.tpl.standup.title': '站会 git 总结',
  'op.tpl.standup.prompt': '总结昨天的 git 提交，生成站会汇报要点',
  'op.created': '已提交闲时任务',
  'op.quota': '剩余额度 \$0',
  'op.earliest': '最早可用 \$0',
  'op.minutes': '\$0 分钟',
  'op.hours': '\$0 小时',
  'op.duration': '用时 \$0',
  'op.queue': '排队中 #\$0',
  'op.status.queued': '排队中',
  'op.status.running': '执行中',
  'op.status.paused': '已暂停',
  'op.status.completed': '已完成',
  'op.status.failed': '失败',
  'op.status.cancelled': '已取消',
  'op.viewResult': '查看结果',
  'op.cancel': '取消任务',
  'op.deleteTitle': '删除闲时任务？',
  'op.deleteBody': '将从历史中移除「\$0」',
  'op.section.active': '进行中',
  'op.section.history': '历史',
  'op.err.prompt': '请填写指令',
  'op.err.noWorkspace': '该设备没有打开的工作区',
  'op.err.codingPlanOnly': '闲时任务仅 Coding Plan 订阅可用',
  'op.err.quota': '本月闲时额度已用尽',
  'op.err.unavailable': '闲时任务服务暂不可用',
  'op.err.other': '操作失败: \$0',
  'settings.notifications': '通知',
  'settings.notificationsHint': '任务完成/失败、闲时结果与自动化触发推送到本机',
  'settings.notify.tasks': '任务事件',
  'settings.notify.offPeak': '闲时事件',
  'settings.notify.auto': '自动化结果',
  'notify.task.done': '任务完成',
  'notify.task.failed': '任务失败',
  'notify.task.interrupted': '任务已中断',
  'notify.offPeak.done': '闲时任务完成',
  'notify.offPeak.failed': '闲时任务失败',
  'notify.auto.done': '自动化触发成功',
  'notify.auto.failed': '自动化触发失败',
  'settings.checkUpdate': '检查更新',
  'update.latest': '已是最新版本',
  'update.newVersion': '发现新版本 v\$0',
  'update.availableBody': '有新的 ZRemote 版本可用。',
  'update.download': '到浏览器下载',
  'update.later': '稍后',
  'update.failed': '检查更新失败: \$0',
  'update.storePending': '请通过 App Store 检查更新',
};

const _en = {
  'app.title': 'ZRemote',
  'devices.empty.title': 'No devices yet',
  'devices.empty.body':
      'Open "Remote Control" in ZCode desktop,\nthen scan or paste the link',
  'devices.add': 'Add device',
  'devices.add.scan': 'Scan QR code',
  'devices.add.scanHint': 'Aim at the ZCode remote-control QR code',
  'devices.add.paste': 'Paste link',
  'devices.add.pasteHint': 'Paste the remote-control URL',
  'devices.add.pasteTitle': 'Paste link',
  'devices.add.pasteHint2': 'https://zcode.z.ai/remote/v4?sid=...&hash=...&t=...',
  'devices.add.cancel': 'Cancel',
  'devices.add.confirm': 'Add',
  'devices.add.savedUnparsed': 'URL could not be parsed but was saved',
  'devices.scan.title': 'Scan to add device',
  'devices.scan.fromGallery': 'Pick a QR image from gallery',
  'devices.scan.cameraError':
      'Camera unavailable: \$0\nUse "pick from gallery" in the top-right instead',
  'devices.scan.cameraInitFailed': 'Camera failed to start',
  'devices.scan.decodeFailed': 'No QR code found in that image',
  'devices.scan.decodeError': 'Image decode failed: \$0',
  'devices.scan.hint':
      'Aim at the ZCode remote-control QR code, or pick a screenshot',
  'devices.lastUsed': 'Last used \$0',
  'devices.neverUsed': 'Never used',
  'devices.menu.rename': 'Rename',
  'devices.menu.pin': 'Pin',
  'devices.menu.unpin': 'Unpin',
  'devices.menu.web': 'Open web version',
  'devices.menu.browser': 'Open in browser',
  'devices.menu.copy': 'Copy link',
  'devices.menu.delete': 'Delete',
  'devices.clipboard.offer':
      'A remote-control link is on the clipboard — add it?',
  'devices.clipboard.add': 'Add',
  'devices.menu.export': 'Export device backup',
  'devices.menu.import': 'Import device backup',
  'devices.rename.title': 'Rename device',
  'devices.rename.hint': 'Device name',
  'devices.rename.save': 'Save',
  'devices.delete.title': 'Delete device',
  'devices.delete.body': 'Delete "\$0"?',
  'devices.delete.confirm': 'Delete',
  'devices.copy.done': 'Link copied',
  'devices.export.done': 'Device backup JSON copied to clipboard',
  'devices.import.title': 'Import devices',
  'devices.import.hint': 'Paste device backup JSON',
  'devices.import.confirm': 'Import',
  'devices.import.done': 'Imported \$0 device(s)',
  'devices.import.invalid': 'Invalid backup format',
  'devices.unnamed': 'Unnamed device',
  'status.online': 'Online',
  'status.connecting': 'Connecting…',
  'status.offline': 'Offline',
  'status.error': 'Native list unavailable — use the web version',
  'status.kicked': 'Taken over by another terminal',
  'status.tasksRunning': '\$0 task(s) running',
  'time.justNow': 'just now',
  'time.minutesAgo': '\$0 min ago',
  'time.hoursAgo': '\$0 h ago',
  'time.daysAgo': '\$0 d ago',
  'time.short.justNow': 'now',
  'time.short.minutes': '\$0m',
  'time.short.hours': '\$0h',
  'time.short.days': '\$0d',
  'tasks.title': 'Tasks',
  'tasks.empty': 'No tasks yet',
  'tasks.loading': 'Loading tasks…',
  'tasks.fallback.title': 'Native list unavailable',
  'tasks.fallback.body':
      'The protocol link is not ready — use the web version for now.',
  'tasks.openWeb': 'Open web version',
  'tasks.retry': 'Retry',
  'tasks.stop': 'Stop',
  'tasks.pause': 'Pause',
  'tasks.resume': 'Resume',
  'tasks.opFailed': 'Operation failed: \$0',
  'tasks.untitled': 'Untitled task',
  'tasks.workspaces': 'Workspace',
  'tasks.pickWorkspace': 'Choose a workspace',
  'tasks.noWorkspaces.title': 'No open workspace on the desktop',
  'tasks.noWorkspaces.body':
      'Open a project in ZCode desktop first, then retry here',
  'tasks.deepLinking': 'Jumping to the task…',
  'phase.running': 'Running',
  'phase.prewarming': 'Prewarming',
  'phase.completedSuccess': 'Completed',
  'phase.completedInterrupted': 'Interrupted',
  'phase.error': 'Error',
  'phase.draft': 'Draft',
  'phase.paused': 'Paused',
  // ---- chat (native conversation) ----
  'chat.appBar': 'Task session',
  'chat.copy': 'Copy',
  'chat.copied': 'Copied',
  'chat.expand': 'Expand',
  'chat.collapse': 'Collapse',
  'chat.empty': 'No messages yet',
  'chat.draftHint': 'Type a message to start a new task',
  'chat.noSession': 'No session yet',
  'chat.noOlder': 'No older messages',
  'chat.loadOlder': 'Load older messages',
  'chat.loadOlder.failed': 'Load failed: \$0',
  'chat.subscribe.failed': 'Subscribe failed: \$0',
  'chat.reconnecting': 'Connection lost, reconnecting…',
  'chat.kicked.title': 'Taken over by another device',
  'chat.kicked.body':
      'Only one terminal may follow a task at a time. Reconnect after the other device exits.',
  'chat.kicked.reconnect': 'Reconnect',
  'chat.creating': 'Creating the session (first run may warm up)…',
  'chat.send.failed': 'Send failed: \$0',
  'chat.op.failed': 'Operation failed: \$0',
  'chat.compact.failed': 'Compact failed',
  'chat.goal.pauseFailed': 'Pause goal failed',
  'chat.goal.resumeFailed': 'Resume goal failed',
  'chat.held.title': 'Queued messages pending',
  'chat.held.body':
      'Sending now clears the queued messages and jumps the queue',
  'chat.held.keep': 'Send to queue',
  'chat.held.clear': 'Send now',
  'chat.reasoning': 'Reasoning',
  'chat.reasoning.thinking': 'Thinking…',
  'chat.turn.worked': 'Worked \$0',
  'chat.time.secOnly': '\$0s',
  'chat.time.minSec': '\$0m \$1s',
  'chat.files.changed': '\$0 files changed',
  'chat.files.undo': 'Undo',
  'chat.subagent': 'Subagent · \$0',
  'chat.bgWorks': '\$0 background tasks running: \$1',
  'chat.tool.input': 'Input',
  'chat.tool.output': 'Output',
  'chat.tool.error': 'Error',
  'chat.tool.wrote': 'Wrote \$0',
  'chat.tool.terminal': 'Terminal',
  'chat.tool.explore': 'Explore',
  'chat.tool.exploreN': 'Explore · \$0 files',
  'chat.marker.compact': 'Compacted · \$0\$1',
  'chat.marker.tokens': ' · \$0→\$1 tokens',
  'chat.marker.forkNotice': 'Forked from a session',
  'chat.marker.forkCreated': 'Fork session created',
  'chat.marker.modelChange': 'Model switch \$0 → \$1',
  'chat.marker.goalSet': 'Goal set: \$0',
  'chat.marker.goalVerify': 'Goal verify round \$0 · \$1',
  'chat.marker.retryNotice': 'Auto retry #\$0 (\$1)',
  'chat.marker.checkpointRestored': 'Checkpoint restored',
  'chat.queue.count': 'Queued \$0',
  'chat.queue.autoOn': 'Auto-send: on',
  'chat.queue.autoOff': 'Auto-send: off',
  'chat.queue.sendNow': 'Send now',
  'chat.queue.edit': 'Edit',
  'chat.queue.edit.title': 'Edit queued message',
  'chat.queue.delete.title': 'Delete queued message?',
  'chat.interact.permission': 'Permission · \$0',
  'chat.interact.waiting': 'Waiting for your input',
  'chat.interact.hint': 'Type a reply…',
  'chat.interact.allowOnce': 'Allow once',
  'chat.interact.allowAlways': 'Always allow',
  'chat.interact.deny': 'Deny',
  'chat.interact.custom': 'Custom',
  'chat.interact.pick': 'Pick',
  'chat.interact.submit': 'Submit',
  'chat.mode.build': 'Build',
  'chat.mode.edit': 'Edit',
  'chat.mode.plan': 'Plan',
  'chat.mode.yolo': 'Auto',
  'chat.followup.queue': 'Queue',
  'chat.followup.guide': 'Guide',
  'chat.sheet.title': 'Model & mode',
  'chat.sheet.draftTitle': 'New task · model & mode',
  'chat.sheet.currentModel': 'Current model: \$0',
  'chat.sheet.thought': 'Thought level',
  'chat.sheet.mode': 'Collaboration mode',
  'chat.sheet.followup': 'Follow-up messages',
  'chat.sheet.other': 'Other settings',
  'chat.sheet.rejected': 'Rejected: \$0',
  'chat.usage.context': 'Context',
  'chat.usage.input': 'Total input',
  'chat.usage.output': 'Total output',
  'chat.usage.cacheRead': 'Cache read',
  'chat.usage.cacheWrite': 'Cache write',
  'chat.json.empty': '(no data)',
  'chat.slash.empty': 'No matching commands',
  'chat.skills.title': 'Pick skills',
  'chat.skills.empty': 'No skills available',
  'chat.input.hint': 'Describe the next change',
  'chat.input.attach': 'Add context',
  'chat.attach.pickFailed': 'File picking failed: \$0',
  'chat.attach.uploading': 'Uploading attachments…',
  'chat.attach.loadFailed': '[image failed to load] \$0',
  'chat.more': 'More',
  'chat.more.rename': 'Rename task',
  'chat.more.rename.hint': 'Task name',
  'chat.more.rename.save': 'Save',
  'chat.more.pin': 'Pin',
  'chat.more.archive': 'Archive',
  'chat.more.unread': 'Mark unread',
  'chat.more.copyPath': 'Copy path',
  'chat.more.copyId': 'Copy task ID',
  'chat.more.copyLink': 'Copy task link',
  'chat.more.linkCopied': 'Task link copied',
  'chat.more.idCopied': 'Task ID copied',
  'chat.more.pathCopied': 'Path copied',
  'chat.more.noPath': 'No workspace path available',
  'chat.more.noLink': 'No task link available',
  'chat.more.compact': 'Compact context',
  'chat.more.usage': 'Usage',
  'chat.more.plans': 'Plans',
  'chat.plans': 'Plans',
  'chat.plans.failed': 'Failed to load plans: \$0',
  'chat.action.editResend': 'Edit & resend',
  'chat.action.edit.title': 'Edit message',
  'chat.action.edit.failed': 'Edit failed: \$0',
  'chat.action.retry': 'Retry turn',
  'chat.action.retry.failed': 'Retry failed',
  'chat.action.fork': 'Fork conversation',
  'chat.action.fork.failed': 'Fork failed',
  'chat.action.rewind': 'Rewind files here',
  'chat.action.rewind.title': 'Rewind files?',
  'chat.action.rewind.body':
      'File changes made after this message will be rolled back; the conversation is kept',
  'chat.action.rewind.confirm': 'Rewind',
  'chat.action.rewind.failed': 'Rewind failed',
  'chat.action.fileChanges': 'View file changes',
  'chat.action.fileChanges.failed': 'Failed to load: \$0',
  'chat.diff.truncated': '… (diff truncated)',
  // ---- task list (official mobile layout) ----
  'tasks.sectionTitle': 'Workspaces & tasks on this device',
  'tasks.stats': '\$0 workspaces · \$1 tasks',
  'tasks.collapseAll': 'Collapse all',
  'tasks.expandAll': 'Expand all',
  'tasks.tidy': 'Tidy',
  'tasks.updatedAt': 'Updated \$0',
  'tasks.taskCount': '\$0 tasks',
  'tasks.local': 'Local',
  'tasks.new': 'New task',
  'tasks.banner.nativeOff': 'The native list is off; enable it in settings',
  'tasks.banner.kicked':
      'Another terminal holds this device connection; retry after it exits',
  'tasks.banner.connecting': 'Connecting to the desktop…',
  'tasks.banner.onlineTitle': 'ZCode Remote Control',
  'tasks.banner.onlineSubtitle': 'Connected to the current desktop window',
  'tasks.banner.onlineDesc':
      'This connection can view the projects, tasks and sessions open on this device. After the QR code expires, reconnect from the desktop app.',
  'tasks.paneHint': 'Pick a task on the left to view its session',
  'tasks.commandSearch': 'Search and run commands available in this workspace',
  'tasks.commandSearch.empty': 'No matching commands',
  'tasks.pinned': 'Pinned',
  'tasks.projects': 'Projects',
  'tasks.search': 'Search',
  'tasks.sidebar.new': 'New task',
  'remote.error.title': 'Cannot reach the desktop device',
  'remote.error.hint': 'Make sure ZCode desktop is running and the network works',
  'remote.reload': 'Reload',
  'settings.title': 'Settings',
  'settings.appearance': 'Appearance',
  'settings.theme': 'Theme',
  'settings.theme.dark': 'Dark',
  'settings.theme.light': 'Light',
  'settings.theme.system': 'System',
  'settings.general': 'General',
  'settings.language': 'Language',
  'settings.language.zh': '中文',
  'settings.language.en': 'English',
  'settings.nativeList': 'Native task list',
  'settings.nativeListHint':
      'Native device status and task list; turn off to use the web version only',
  'settings.data': 'Data',
  'settings.usageStats': 'Usage statistics',
  'settings.usageStatsHint': 'Stored on this device only',
  'settings.about': 'About ZRemote',
  'about.version': 'Version',
  'about.github': 'GitHub repository',
  'about.licenses': 'Open-source licenses',
  'about.privacy': 'Privacy policy',
  'about.tos': 'Terms of Service',
  'about.disclaimer':
      'ZRemote is an unofficial community client, not affiliated with Zhipu AI or ZCode.',
  'usage.title': 'Usage statistics',
  'usage.summary.devices': 'Devices',
  'usage.summary.opens': 'Total opens',
  'usage.perDevice': 'Per device',
  'usage.opens': '\$0 opens',
  'usage.addedAt': 'Added \$0',
  'usage.neverUsed': 'Never used',
  'tasks.menu.usage': 'Usage',
  'tasks.menu.providers': 'Model providers',
  'usageRpc.title': 'Usage',
  'usageRpc.loadFailed': 'Load failed: \$0',
  'usageRpc.remaining': 'Remaining quota',
  'usageRpc.remainingDetail': '\$0% left · resets \$1',
  'usageRpc.limits': 'Quota limits',
  'usageRpc.subscription': 'Subscription',
  'usageRpc.product': 'Product',
  'usageRpc.billing': 'Billing cycle',
  'usageRpc.renew': 'Renews',
  'usageRpc.expire': 'Expires',
  'usageRpc.used': 'Used \$0',
  'usageRpc.left': '\$0 left',
  'usageRpc.resetAt': 'Resets \$0',
  'providers.title': 'Model providers',
  'providers.add': 'Add',
  'providers.addTitle': 'Add model provider',
  'providers.name': 'Name',
  'providers.apiFormat': 'API format',
  'providers.apiKey': 'API Key (optional)',
  'providers.models': 'Model IDs (comma-separated)',
  'providers.modelsCount': '\$0 models',
  'providers.disabled': 'Disabled: \$0',
  'providers.loadFailed': 'Load failed: \$0',
  'providers.toggleFailed': 'Toggle failed: \$0',
  'providers.deleteFailed': 'Delete failed: \$0',
  'providers.addFailed': 'Add failed: \$0',
  'providers.added': 'Provider added',
  'providers.deleteTitle': 'Delete model provider?',
  'providers.deleteBody': 'This deletes "\$0".',
  'sched.menu': 'Scheduled & automations',
  'sched.title': 'Scheduled & automations',
  'sched.section.server': 'Device automations',
  'sched.section.local': 'Local scheduled messages',
  'sched.openAuto': 'Manage device automations',
  'sched.add': 'New message',
  'sched.empty': 'No scheduled messages',
  'sched.noDevices': 'Add a device first',
  'sched.created': 'Scheduled message created',
  'sched.device': 'Device',
  'sched.message': 'Message',
  'sched.time': 'Send at',
  'sched.pending': 'Pending',
  'sched.sent': 'Sent',
  'sched.failed': 'Failed',
  'sched.hint':
      'Keep the app in the foreground at fire time, with the native task list enabled',
  'tasks.menu.automations': 'Automations',
  'auto.title': 'Automations',
  'auto.subtitle': 'Scheduled by the desktop — the app can be offline',
  'auto.add': 'New automation',
  'auto.edit': 'Edit automation',
  'auto.empty': 'No automations yet',
  'auto.loading': 'Loading automations…',
  'auto.loadFailed': 'Load failed: \$0',
  'auto.unavailable.title': 'Device automations unavailable',
  'auto.unavailable.body':
      'The device is offline or the protocol handshake is unfinished. Use "local scheduled messages" as a fallback and manage automations once the device is back.',
  'auto.opFailed': 'Operation failed: \$0',
  'auto.created': 'Automation created',
  'auto.saved': 'Saved',
  'auto.deleted': 'Deleted',
  'auto.delete.title': 'Delete automation?',
  'auto.delete.body': 'This deletes "\$0".',
  'auto.enabled': 'Enabled',
  'auto.disabled': 'Disabled',
  'auto.name': 'Title',
  'auto.prompt': 'Instruction',
  'auto.hint': 'Triggered by the desktop scheduler; no need to keep the app online',
  'auto.trigger': 'Trigger rule',
  'auto.trigger.cron': 'Cron',
  'auto.trigger.interval': 'Interval',
  'auto.trigger.oneShot': 'One-shot',
  'auto.cronExpr': 'Cron expression',
  'auto.cronHint': '5 fields, e.g. 0 9 * * 1-5 for weekdays at 9',
  'auto.interval': 'Every',
  'auto.intervalUnit.label': 'Unit',
  'auto.intervalUnit.minute': 'minute(s)',
  'auto.intervalUnit.hour': 'hour(s)',
  'auto.intervalUnit.day': 'day(s)',
  'auto.intervalUnit.week': 'week(s)',
  'auto.intervalUnit.month': 'month(s)',
  'auto.intervalUnit.year': 'year(s)',
  'auto.recurring': 'Repeat forever',
  'auto.maxRuns': 'Max runs',
  'auto.maxRunsN': 'max \$0 runs',
  'auto.delayMinutes': 'Delay (minutes)',
  'auto.delayHint': 'Delayed from creation, up to 1 year',
  'auto.model': 'Model (optional)',
  'auto.mode': 'Mode (optional)',
  'auto.mode.default': 'Default',
  'auto.thoughtLevel': 'Thought level (optional)',
  'auto.targetTask': 'Target task ID (optional)',
  'auto.advanced': 'More options',
  'auto.cronAt': 'Cron \$0',
  'auto.every': 'Every \$0 \$1',
  'auto.once': 'One-shot · after \$0',
  'auto.minutes': '\$0 min',
  'auto.hours': '\$0 h',
  'auto.days': '\$0 d',
  'auto.lastRun': 'Last run \$0',
  'auto.err.title': 'Title is required',
  'auto.err.prompt': 'Instruction is required',
  'auto.err.cron': 'Cron expression is required',
  'auto.err.interval': 'Interval must be a positive integer',
  'auto.err.delay': 'Delay must be between 1 minute and 1 year',
  'tasks.menu.offPeak': 'Off-peak tasks',
  'op.title': 'Off-peak tasks',
  'op.subtitle': 'Free runs in compute-rich windows · Coding Plan',
  'op.hint':
      'Queued after submitting, executed free in compute-rich windows; requires a Coding Plan subscription',
  'op.add': 'New off-peak task',
  'op.submit': 'Submit',
  'op.empty': 'No off-peak tasks yet',
  'op.loading': 'Loading off-peak tasks…',
  'op.loadFailed': 'Load failed: \$0',
  'op.unavailable.title': 'Off-peak tasks unavailable',
  'op.unavailable.body':
      'The device is offline or the protocol handshake is unfinished; try again later.',
  'op.name': 'Title',
  'op.prompt': 'Instruction',
  'op.model': 'Model (optional)',
  'op.earliestAt': 'Earliest available (optional)',
  'op.earliest.any': 'Any — run as soon as queued',
  'op.keepAwake': 'Keep awake',
  'op.keepAwakeHint':
      'Keep the device connection alive so results arrive promptly',
  'op.permission': 'Permission mode',
  'op.permission.build': 'build',
  'op.permission.plan': 'plan',
  'op.permission.yolo': 'yolo',
  'op.tpl.ci.title': 'CI flaky report',
  'op.tpl.ci.prompt':
      'Analyze recent CI failures, identify flaky tests and write a report',
  'op.tpl.docs.title': 'Docs sync check',
  'op.tpl.docs.prompt':
      'Check whether docs touched by recent code changes need updating and list stale entries',
  'op.tpl.standup.title': 'Standup git summary',
  'op.tpl.standup.prompt':
      'Summarize yesterday\'s git commits into standup notes',
  'op.created': 'Off-peak task submitted',
  'op.quota': '\$0 quota left',
  'op.earliest': 'Earliest \$0',
  'op.minutes': '\$0 min',
  'op.hours': '\$0 h',
  'op.duration': 'Took \$0',
  'op.queue': 'Queued #\$0',
  'op.status.queued': 'Queued',
  'op.status.running': 'Running',
  'op.status.paused': 'Paused',
  'op.status.completed': 'Completed',
  'op.status.failed': 'Failed',
  'op.status.cancelled': 'Cancelled',
  'op.viewResult': 'View result',
  'op.cancel': 'Cancel task',
  'op.deleteTitle': 'Delete off-peak task?',
  'op.deleteBody': 'This removes "\$0" from history.',
  'op.section.active': 'Active',
  'op.section.history': 'History',
  'op.err.prompt': 'Instruction is required',
  'op.err.noWorkspace': 'No open workspace on this device',
  'op.err.codingPlanOnly':
      'Off-peak tasks require a Coding Plan subscription',
  'op.err.quota': 'Monthly off-peak quota is used up',
  'op.err.unavailable': 'Off-peak service is temporarily unavailable',
  'op.err.other': 'Operation failed: \$0',
  'settings.notifications': 'Notifications',
  'settings.notificationsHint':
      'Task completions, off-peak results and automation runs pushed locally',
  'settings.notify.tasks': 'Task events',
  'settings.notify.offPeak': 'Off-peak events',
  'settings.notify.auto': 'Automation results',
  'notify.task.done': 'Task completed',
  'notify.task.failed': 'Task failed',
  'notify.task.interrupted': 'Task interrupted',
  'notify.offPeak.done': 'Off-peak task completed',
  'notify.offPeak.failed': 'Off-peak task failed',
  'notify.auto.done': 'Automation triggered',
  'notify.auto.failed': 'Automation run failed',
  'settings.checkUpdate': 'Check for updates',
  'update.latest': 'Up to date',
  'update.newVersion': 'New version v\$0',
  'update.availableBody': 'A new ZRemote version is available.',
  'update.download': 'Download in browser',
  'update.later': 'Later',
  'update.failed': 'Update check failed: \$0',
  'update.storePending': 'Check for updates in the App Store',
};
