import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

/// UI preferences: locale (zh-CN / en-US), the native task-list switch and
/// the notification switches (master + per channel).
class UiSettings extends ChangeNotifier {
  static const _localeKey = 'zlinker_ui_locale';
  static const _nativeListKey = 'zlinker_native_list';
  static const _notifyKey = 'zlinker_notify';
  static const _notifyTasksKey = 'zlinker_notify_tasks';
  static const _notifyOffPeakKey = 'zlinker_notify_offpeak';
  static const _notifyAutoKey = 'zlinker_notify_auto';

  String locale = 'zh-CN';
  bool nativeListEnabled = true;
  bool notificationsEnabled = true;
  bool notifyTasksEnabled = true;
  bool notifyOffPeakEnabled = true;
  bool notifyAutoEnabled = true;

  Future<void> load() async {
    final prefs = await SharedPreferences.getInstance();
    locale = prefs.getString(_localeKey) ?? 'zh-CN';
    nativeListEnabled = prefs.getBool(_nativeListKey) ?? true;
    notificationsEnabled = prefs.getBool(_notifyKey) ?? true;
    notifyTasksEnabled = prefs.getBool(_notifyTasksKey) ?? true;
    notifyOffPeakEnabled = prefs.getBool(_notifyOffPeakKey) ?? true;
    notifyAutoEnabled = prefs.getBool(_notifyAutoKey) ?? true;
    notifyListeners();
  }

  Future<void> setLocale(String value) async {
    locale = value;
    notifyListeners();
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString(_localeKey, value);
  }

  Future<void> setNativeListEnabled(bool value) async {
    nativeListEnabled = value;
    notifyListeners();
    final prefs = await SharedPreferences.getInstance();
    await prefs.setBool(_nativeListKey, value);
  }

  Future<void> setNotificationsEnabled(bool value) async {
    notificationsEnabled = value;
    notifyListeners();
    final prefs = await SharedPreferences.getInstance();
    await prefs.setBool(_notifyKey, value);
  }

  Future<void> setNotifyTasksEnabled(bool value) async {
    notifyTasksEnabled = value;
    notifyListeners();
    final prefs = await SharedPreferences.getInstance();
    await prefs.setBool(_notifyTasksKey, value);
  }

  Future<void> setNotifyOffPeakEnabled(bool value) async {
    notifyOffPeakEnabled = value;
    notifyListeners();
    final prefs = await SharedPreferences.getInstance();
    await prefs.setBool(_notifyOffPeakKey, value);
  }

  Future<void> setNotifyAutoEnabled(bool value) async {
    notifyAutoEnabled = value;
    notifyListeners();
    final prefs = await SharedPreferences.getInstance();
    await prefs.setBool(_notifyAutoKey, value);
  }
}

class UiSettingsProvider extends InheritedWidget {
  final UiSettings settings;

  const UiSettingsProvider({
    super.key,
    required this.settings,
    required super.child,
  });

  static UiSettings? of(BuildContext context) => context
      .dependOnInheritedWidgetOfExactType<UiSettingsProvider>()
      ?.settings;

  @override
  bool updateShouldNotify(UiSettingsProvider oldWidget) =>
      settings != oldWidget.settings;
}

/// Lightweight i18n lookup (single-file table scheme).
String tr(BuildContext context, String key) =>
    trLocale(UiSettingsProvider.of(context)?.locale ?? 'zh-CN', key);

/// Context-free lookup for surfaces without a BuildContext (push
/// notifications render outside the widget tree).
String trLocale(String locale, String key) {
  final table = locale.startsWith('en') ? _en : _zh;
  return table[key] ?? _zh[key] ?? key;
}

/// [tr] with positional substitution: `$0`, `$1`, ... in the template are
/// replaced by [args] in order.
String trP(BuildContext context, String key, List<String> args) {
  var out = tr(context, key);
  for (var i = 0; i < args.length; i++) {
    out = out.replaceAll('\$$i', args[i]);
  }
  return out;
}

/// Relative-time formatting using the 'time.*' table keys.
String relativeTime(BuildContext context, int ms) {
  final diff = DateTime.now().difference(
    DateTime.fromMillisecondsSinceEpoch(ms),
  );
  // Future timestamps (an automation's 下次运行) read as "in n …".
  if (diff.isNegative) {
    final future = -diff;
    if (future.inMinutes < 60) {
      return trP(context, 'time.minutesLater', ['${future.inMinutes}']);
    }
    if (future.inHours < 24) {
      return trP(context, 'time.hoursLater', ['${future.inHours}']);
    }
    if (future.inDays < 30) {
      return trP(context, 'time.daysLater', ['${future.inDays}']);
    }
    return DateTime.fromMillisecondsSinceEpoch(
      ms,
    ).toLocal().toString().substring(0, 10);
  }
  if (diff.inMinutes < 1) return tr(context, 'time.justNow');
  if (diff.inHours < 1) {
    return trP(context, 'time.minutesAgo', ['${diff.inMinutes}']);
  }
  if (diff.inDays < 1) {
    return trP(context, 'time.hoursAgo', ['${diff.inHours}']);
  }
  if (diff.inDays < 30) {
    return trP(context, 'time.daysAgo', ['${diff.inDays}']);
  }
  return DateTime.fromMillisecondsSinceEpoch(
    ms,
  ).toLocal().toString().substring(0, 10);
}

/// Official list/sidebar compact relative time: `27分` / `1小时` / `13天`.
String relativeTimeShort(BuildContext context, int ms) {
  final diff = DateTime.now().difference(
    DateTime.fromMillisecondsSinceEpoch(ms),
  );
  if (diff.inMinutes < 1) return tr(context, 'time.short.justNow');
  if (diff.inHours < 1) {
    return trP(context, 'time.short.minutes', ['${diff.inMinutes}']);
  }
  if (diff.inDays < 1) {
    return trP(context, 'time.short.hours', ['${diff.inHours}']);
  }
  if (diff.inDays < 30) {
    return trP(context, 'time.short.days', ['${diff.inDays}']);
  }
  return DateTime.fromMillisecondsSinceEpoch(
    ms,
  ).toLocal().toString().substring(0, 10);
}

const _zh = {
  'app.title': 'ZLinker',
  'devices.empty.title': '还没有设备',
  'devices.empty.body': '在桌面 ZCode 中打开「远程控制」，\n扫码或粘贴链接即可添加设备',
  'devices.add': '添加设备',
  'devices.add.scan': '扫码添加',
  'devices.add.scanHint': '对准桌面端 ZCode 远程控制二维码',
  'devices.add.paste': '粘贴链接添加',
  'devices.add.pasteHint': '粘贴远程控制 URL',
  'devices.add.pasteTitle': '粘贴链接添加',
  'devices.add.pasteHint2':
      'https://zcode.z.ai/remote/v4?sid=...&hash=...&t=...',
  'devices.add.cancel': '取消',
  'devices.add.confirm': '添加',
  'devices.add.savedUnparsed': 'URL 无法解析，但仍已保存',
  'devices.scan.title': '扫码添加设备',
  'devices.scan.fromGallery': '从相册选择二维码图片',
  'devices.scan.cameraError': '相机不可用: \$0\n可改用右上角从图片识别',
  'devices.scan.cameraInitFailed': '相机初始化失败',
  'devices.scan.decodeFailed': '未能从图片中识别二维码',
  'devices.scan.decodeError': '图片识别失败: \$0',
  'devices.scan.hint': '对准桌面端 ZCode 远程控制二维码，或从相册选择二维码截图',
  'devices.lastUsed': '上次使用 \$0',
  'devices.neverUsed': '从未使用',
  'devices.menu.rename': '重命名',
  'devices.menu.pin': '置顶',
  'devices.menu.unpin': '取消置顶',
  'devices.menu.web': '网页版打开',
  'devices.menu.browser': '在浏览器中打开',
  'devices.menu.copy': '复制链接',
  'devices.menu.delete': '删除',
  'devices.clipboard.offer': '剪贴板里有一条远程控制链接，要添加吗？',
  'devices.clipboard.add': '添加',
  'devices.menu.export': '导出设备备份',
  'devices.menu.import': '导入设备备份',
  'devices.rename.title': '重命名设备',
  'devices.rename.hint': '设备名称',
  'devices.rename.save': '保存',
  'devices.delete.title': '删除设备',
  'devices.delete.body': '确定要删除「\$0」吗？',
  'devices.delete.confirm': '删除',
  'devices.copy.done': '链接已复制',
  'devices.export.done': '已复制设备备份 JSON 到剪贴板',
  'devices.import.title': '导入设备',
  'devices.import.hint': '粘贴设备备份 JSON',
  'devices.import.confirm': '导入',
  'devices.import.done': '已导入 \$0 台设备',
  'devices.import.invalid': '备份格式无效',
  'devices.unnamed': '未命名设备',
  'status.online': '在线',
  'status.connecting': '连接中…',
  'status.offline': '离线',
  'status.error': '原生列表不可用，请用网页版',
  'status.kicked': '已被其他终端接管',
  'status.tasksRunning': '\$0 个任务运行中',
  'time.justNow': '刚刚',
  'time.minutesAgo': '\$0 分钟前',
  'time.hoursAgo': '\$0 小时前',
  'time.daysAgo': '\$0 天前',
  'time.minutesLater': '\$0 分钟后',
  'time.hoursLater': '\$0 小时后',
  'time.daysLater': '\$0 天后',
  'time.short.justNow': '刚刚',
  'time.short.minutes': '\$0分',
  'time.short.hours': '\$0小时',
  'time.short.days': '\$0天',
  'tasks.title': '任务',
  'tasks.empty': '暂无任务',
  'tasks.loading': '正在获取任务列表…',
  'tasks.fallback.title': '原生列表不可用',
  'tasks.fallback.body': '协议连接未就绪，可先用网页版操作此设备。',
  'tasks.openWeb': '网页版打开',
  'tasks.retry': '重试',
  'tasks.stop': '停止',
  'tasks.pause': '暂停',
  'tasks.resume': '恢复',
  'tasks.opFailed': '操作失败: \$0',
  'tasks.untitled': '未命名任务',
  'tasks.workspaces': '工作区',
  'tasks.pickWorkspace': '选择工作区',
  'tasks.noWorkspaces.title': '桌面端没有打开的工作区',
  'tasks.noWorkspaces.body': '请先在桌面 ZCode 中打开一个项目，再回到这里重试',
  'tasks.deepLinking': '正在直达任务…',
  'phase.running': '运行中',
  'phase.prewarming': '预热中',
  'phase.completedSuccess': '已完成',
  'phase.completedInterrupted': '已中断',
  'phase.error': '出错',
  'phase.draft': '草稿',
  'phase.paused': '已暂停',
  'phase.idle': '待命',
  // ---- task actions & tags (web taskList/task-item menu parity) ----
  'tasks.awaiting': '等待确认',
  'tasks.renamePlaceholder': '任务名称',
  'tasks.action.pin': '置顶',
  'tasks.action.unpin': '取消置顶',
  'tasks.action.rename': '重命名',
  'tasks.action.archive': '归档',
  'tasks.action.unarchive': '取消归档',
  'tasks.action.archiveView': '查看归档',
  'tasks.action.unarchiveView': '退出归档视图',
  'tasks.action.markUnread': '标记为未读',
  'tasks.action.markRead': '标记为已读',
  'tasks.action.delete': '删除',
  'tasks.action.deleteTitle': '删除这个任务？',
  'tasks.action.deleteDesc': '任务「\$0」会从当前工作区移除，现有记录无法恢复。',
  'tasks.workspaceKind.local': '本地',
  'tasks.workspaceKind.conversation': '对话',
  'tasks.workspaceKind.remote': '远程',
  'common.cancel': '取消',
  'common.retryLater': '稍后重试',
  'common.save': '保存',
  // ---- webRemoteControl failure states (official copy) ----
  'remote.failure.session-not-found': '当前 Web 远程控制链接已经失效，请回到桌面端重新开启一次。',
  'remote.failure.session-expired': '这次 Web 远程控制会话已经结束了，需要在桌面端重新生成新的链接。',
  'remote.failure.session-conflict': '这个链接已经被其他页面占用，请关闭旧页面后重新扫码。',
  'remote.failure.kicked': 'relay 已踢出这次配对，请关闭其他页面后从桌面端重新生成二维码。',
  'remote.failure.workspace-closed': '桌面端共享的窗口已经关闭，请回到桌面端重新发起访问。',
  'remote.failure.desktop-disconnected': '桌面端已经断开连接，当前 Web 远程控制无法继续使用。',
  'remote.failure.invalid-mobile-connection': '当前手机连接已失效，请刷新页面后重新连接。',
  'remote.failure.desktop-bootstrap-timeout': '桌面端响应超时，请确认窗口仍在运行后刷新页面。',
  'remote.failure.connection-recovery-timeout':
      '手机端连接恢复超时，当前 Web 远程控制暂时无法继续同步。',
  'remote.failure.relay-unavailable': '外部 relay 连接不可用，请确认桌面端在线后重试。',
  'remote.failure.unsupported-action': '当前是 Web 远程控制模式，只支持访问桌面端当前窗口已经打开的工作区。',
  'remote.failure.unexpected-error': '无法启动移动端远程控制，请回到桌面端重试。',
  // ---- chat (native conversation) ----
  'chat.appBar': '任务会话',
  'chat.copy': '复制',
  'chat.copied': '已复制',
  'chat.expand': '展开',
  'chat.collapse': '收起',
  'chat.empty': '暂无消息',
  'chat.draftHint': '输入消息开始新任务',
  'chat.noSession': '尚无会话',
  'chat.noOlder': '没有更早的消息了',
  'chat.loadOlder.stale': '会话数据已刷新，请重试',
  'chat.loadOlder': '加载更早消息',
  'chat.loadOlder.failed': '加载失败: \$0',
  'chat.subscribe.failed': '订阅失败: \$0',
  'chat.reconnecting': '连接已断开，正在自动重连…',
  'chat.kicked.title': '已被其他设备接管',
  'chat.kicked.body': '同一任务同时只允许一个终端连接，可在其他设备退出后重新连接。',
  'chat.kicked.reconnect': '重新连接',
  'chat.creating': '正在创建会话（首次可能需要预热）…',
  'chat.send.failed': '发送失败: \$0',
  'chat.op.failed': '操作失败: \$0',
  'chat.compact.failed': '压缩失败',
  'chat.goal.pauseFailed': '暂停目标失败',
  'chat.goal.resumeFailed': '恢复目标失败',
  'chat.held.title': '有排队中的消息',
  'chat.held.body': '立即发送将清空排队消息并插队执行',
  'chat.held.keep': '排队发送',
  'chat.held.clear': '立即发送',
  'chat.reasoning': '思考过程',
  'chat.reasoning.thinking': '思考中…',
  'chat.turn.worked': '已工作 \$0',
  'chat.time.secOnly': '\$0 秒',
  'chat.time.minSec': '\$0 分 \$1 秒',
  'chat.files.changed': '\$0 个文件已更改',
  'chat.files.undo': '撤销',
  'chat.subagent': '子代理 · \$0',
  'chat.bgWorks': '后台任务 \$0 个运行中: \$1',
  'chat.tool.input': '输入',
  'chat.tool.output': '输出',
  'chat.tool.error': '错误',
  'chat.tool.wrote': '已写入 \$0',
  'chat.tool.terminal': '终端',
  'chat.tool.explore': '探索',
  'chat.tool.exploreN': '探索 · \$0 文件',
  'chat.marker.compact': '压缩上下文 · \$0\$1',
  'chat.marker.tokens': ' · \$0→\$1 tokens',
  'chat.marker.forkNotice': '从会话分叉而来',
  'chat.marker.forkCreated': '已创建分叉会话',
  'chat.marker.modelChange': '模型已切换 \$0 → \$1',
  'chat.marker.goalSet': '设定目标: \$0',
  'chat.marker.goalVerify': '目标验证 第\$0轮 · \$1',
  'chat.marker.retryNotice': '自动重试 第\$0次 (\$1)',
  'chat.marker.checkpointRestored': '已恢复检查点',
  'chat.queue.count': '排队消息 \$0',
  'chat.tool.askQuestion.asking': '正在询问',
  'chat.tool.askQuestion.asked': '已询问',
  'chat.tool.askQuestion.askedN': '已询问 · \$0 个问题',
  'chat.tool.askQuestion.autoContinued': '未回答，已自动继续',
  'chat.tool.taskOutput.kind': '任务输出',
  'chat.tool.taskOutput.fetching': '正在获取任务输出',
  'chat.tool.taskOutput.running': '任务运行中',
  'chat.tool.taskOutput.failed': '获取输出失败',
  'chat.tool.taskOutput.denied': '获取已拒绝',
  'chat.tool.taskOutput.stopped': '获取已停止',
  'chat.tool.taskOutput.retrieved': '已获取',
  'chat.tool.taskStop.kind': '停止任务',
  'chat.tool.taskStop.stopping': '正在停止任务',
  'chat.tool.taskStop.failed': '停止任务失败',
  'chat.tool.taskStop.denied': '停止操作已拒绝',
  'chat.tool.taskStop.cancelled': '停止操作已取消',
  'chat.tool.taskStop.stopped': '已停止',
  'chat.tool.send.kind': '发送消息',
  'chat.tool.send.sending': '发送中',
  'chat.tool.send.sent': '已发送',
  'chat.tool.send.failed': '发送失败',
  'chat.tool.send.denied': '发送已拒绝',
  'chat.tool.send.stopped': '发送已停止',
  'chat.tool.group.terminal': '终端',
  'chat.tool.group.count': '\$0 个命令',
  'chat.tool.group.failed': '\$0 个失败',
  'chat.tool.group.stopped': '\$0 个已停止',
  'chat.mention.title': '提及',
  'chat.mention.selectItem': '选择要插入到输入框里的引用',
  'chat.mention.searchHint': '输入内容以搜索文件、技能或会话',
  'chat.mention.emptyResults': '没有匹配的提及结果',
  'chat.mention.category.files': '文件',
  'chat.mention.category.files.description': '搜索工作区文件并插入引用',
  'chat.mention.category.skills': '技能',
  'chat.mention.category.skills.description': '插入技能引用',
  'chat.mention.category.subagents': '子智能体',
  'chat.mention.category.subagents.description': '插入子智能体引用',
  'chat.mention.category.sessions': '会话',
  'chat.mention.category.sessions.description': '插入会话引用',
  'goalPanel.title': '目标',
  'goalPanel.completedN': '已完成 \$0 项',
  'goalPanel.duration.s': '\$0 秒',
  'goalPanel.duration.ms': '\$0 分 \$1 秒',
  'goalPanel.runningFor': '已运行 \$0 分 \$1 秒',
  'goalPanel.agents': '智能体',
  'goalPanel.agentsRunning': '\$0 运行',
  'chat.queue.autoOn': '自动发送: 开',
  'chat.queue.moveUp': '上移',
  'chat.queue.moveDown': '下移',
  'chat.interact.snooze': '稍后自动继续',
  'chat.bgWorks.cancel': '取消此后台任务',
  'chat.rewind.checking': '正在检查可撤销文件…',
  'chat.rewind.safeTitle': '以下文件可以安全撤销',
  'chat.rewind.unsafeTitle': '存在不能安全撤销的文件',
  'chat.rewind.cannotApply': '存在不能安全撤销的文件，未写入任何文件。',
  'chat.rewind.confirm': '撤销这些更改',
  'chat.queue.autoOff': '自动发送: 关',
  'chat.queue.sendNow': '立即发送',
  'chat.queue.edit': '编辑',
  'chat.queue.edit.title': '编辑排队消息',
  'chat.queue.delete.title': '删除排队消息？',
  'chat.interact.permission': '权限请求 · \$0',
  'chat.interact.waiting': '等待你的输入',
  'chat.interact.hint': '输入回复…',
  'chat.interact.allowOnce': '允许一次',
  'chat.interact.allowAlways': '总是允许',
  'chat.interact.deny': '拒绝',
  'chat.interact.custom': '自定义',
  'chat.interact.pick': '选择',
  'chat.interact.submit': '提交',
  'chat.interact.plan.title': '计划确认',
  'chat.interact.plan.viewPlan': '查看计划',
  'chat.interact.plan.feedback': '反馈意见（可选，拒绝时作为理由）',
  'chat.interact.plan.approve': '批准并继续',
  'chat.interact.plan.decline': '拒绝',
  'chat.interact.form.submit': '提交回答',
  'chat.interact.form.cancel': '取消',
  'chat.interact.form.custom': '自定义回答…',
  'chat.interact.form.multi': '多选',
  'chat.interact.hook.title': '工作区 Hook 审核',
  'chat.interact.hook.warning': '这些 Hooks 来自工作区配置，可能会执行代码',
  'chat.interact.hook.trust': '信任所选 Hooks',
  'chat.interact.hook.empty': '没有待审核的 Hook',
  'chat.mode.build': '变更前确认',
  'chat.mode.build.desc': '改文件前先问我。',
  'chat.mode.edit': '自动编辑',
  'chat.mode.edit.desc': '自动编辑文件。',
  'chat.mode.plan': '计划模式',
  'chat.mode.plan.desc': '编辑前先出计划。',
  'chat.mode.yolo': '完全访问',
  'chat.mode.yolo.desc': '减少确认次数。',
  'chat.followup.queue': '排队',
  'chat.followup.guide': '引导',
  'chat.sheet.title': '模型与模式',
  'chat.sheet.draftTitle': '新任务 · 模型与模式',
  'chat.sheet.currentModel': '当前模型: \$0',
  'chat.sheet.thought': '思考等级',
  'chat.sheet.mode': '协作模式',
  'chat.sheet.followup': '后续消息',
  'chat.sheet.other': '其他配置',
  'chat.sheet.rejected': '被拒绝: \$0',
  'chat.usage.context': '上下文',
  'chat.usage.input': '累计输入',
  'chat.usage.output': '累计输出',
  'chat.usage.cacheRead': '缓存读取',
  'chat.usage.cacheWrite': '缓存写入',
  'chat.json.empty': '（无数据）',
  'chat.slash.empty': '没有匹配的命令',
  'chat.skills.title': '选择 Skills',
  'chat.skills.empty': '没有可用的 Skills',
  'chat.input.hint': '提出后续修改要求',
  'chat.input.attach': '添加上下文',
  'chat.input.skills': '选择 Skill',
  'chat.attach.pickFailed': '选择文件失败: \$0',
  'chat.attach.uploading': '正在上传附件…',
  'chat.attach.loadFailed': '[图片加载失败] \$0',
  'chat.more': '更多',
  'chat.more.rename': '重命名任务',
  'chat.more.rename.hint': '任务名称',
  'chat.more.rename.save': '保存',
  'chat.more.pin': '置顶任务',
  'chat.more.unpin': '取消置顶任务',
  'chat.more.archive': '归档任务',
  'chat.more.unread': '标记为未读',
  'chat.more.copyPath': '复制路径',
  'chat.more.copyId': '复制会话 ID',
  'chat.more.copyLink': '复制任务链接',
  'chat.more.linkCopied': '任务链接已复制',
  'chat.more.idCopied': '任务 ID 已复制',
  'chat.more.pathCopied': '路径已复制',
  'chat.more.noPath': '没有可用的工作区路径',
  'chat.more.noLink': '没有可用的任务链接',
  'chat.more.compact': '压缩上下文',
  'chat.more.usage': '用量统计',
  'chat.more.plans': '计划',
  'chat.plans': '计划',
  'chat.plans.failed': '获取计划失败: \$0',
  'chat.plans.current': '当前计划',
  'chat.plans.history': '历史计划',
  'chat.plans.empty': '暂无计划',
  'chat.plans.planN': '计划 \$0',
  'chat.files.reverted': '这轮变更已被回退',
  'chat.rewind.done': '已回退到该轮之前的状态',
  'chat.status.gitDirty': '\$0 个文件未提交',
  'chat.status.section.workflows': '工作流',
  'chat.statusPanel.todo': '进程',
  'chat.status.section.terminals': '终端',
  'chat.status.section.runningCount': '\$0 个后台运行',
  'chat.status.workflowUnnamed': '工作流脚本',
  'chat.status.workflowSteps': '\$0/\$1 步',
  'chat.workflow.status.pending': '待启动',
  'chat.workflow.status.running': '运行中',
  'chat.workflow.status.completed': '已完成',
  'chat.workflow.status.errored': '出错',
  'chat.workflow.status.stopped': '已停止',
  'chat.status.bash': '终端',
  'chat.search.tooltip': '搜索',
  'chat.search.hint': '搜索消息',
  'chat.search.count': '\$0/\$1',
  'chat.search.none': '无结果',
  'chat.search.prev': '上一个',
  'chat.search.next': '下一个',
  'chat.history.tooltip': '输入历史',
  'chat.history.title': '最近输入',
  'chat.history.empty': '暂无输入历史',
  'chat.more.export': '导出 Markdown',
  'chat.export.title': '导出对话',
  'chat.export.copy': '复制全文',
  'chat.export.save': '保存为 .md 文件',
  'chat.export.saved': '已保存 Markdown 文件',
  'chat.export.failed': '导出失败: \$0',
  'chat.export.role.user': '用户',
  'chat.export.role.assistant': '助手',
  'chat.tool.cua.kind': '电脑操作',
  'chat.tool.cua.done': '完成',
  'chat.tool.cua.failed': '失败',
  'chat.tool.cron.kind': '定时任务',
  'chat.tool.cron.updated': '更新定时任务',
  'chat.tool.cron.offpeak': '闲时任务',
  'chat.tool.workflow.kind': '工作流',
  'chat.workflow.card.kindWriting': '正在编写工作流',
  'chat.workflow.card.kindRan': '工作流',
  'chat.workflow.card.kindAmendWriting': '正在调整工作流',
  'chat.workflow.card.kindAmendRan': '工作流调整',
  'chat.workflow.card.created': '已编译',
  'chat.workflow.card.createFailed': '编译失败',
  'chat.workflow.card.phases': '\$0 个阶段',
  'chat.workflow.card.agents': '\$0 个子代理',
  'chat.workflow.card.working': '\$0 个工作中',
  'chat.workflow.card.diagnostics': '另外 \$0 条诊断',
  'chat.workflow.card.unphased': '未分阶段',
  'chat.workflow.card.artifactsMore': '另外 \$0 个产物',
  'chat.workflow.stop.user': '手动停止',
  'chat.workflow.stop.model': '模型停止',
  'chat.workflow.stop.provider': '供应商停止',
  'chat.workflow.stop.interrupted': '被中断',
  'chat.workflow.stop.superseded': '已被替代',
  'chat.workflow.run.resumable': '可恢复',
  'chat.workflow.actorNotStarted': '该子代理尚未启动',
  'wrp.title': '运行详情',
  'wrp.fallbackName': '工作流脚本',
  'wrp.stop': '停止运行',
  'wrp.resume': '恢复运行',
  'wrp.usage': '用量：\$0 tokens · \$1 步',
  'wrp.lineage': '修订自 \$0',
  'wrp.phases': '阶段',
  'wrp.artifacts': '产物',
  'wrp.artifacts.empty': '此 run 没有发布产物',
  'wrp.artifacts.items': '\$0 条记录',
  'wrp.questions': '待回答',
  'wrp.action.rejected': '操作被拒绝: \$0',
  'chat.workflow.card.noAgents': '暂无子代理',
  'chat.tool.workflow.creating': '创建中',
  'chat.tool.workflow.created': '已创建',
  'chat.tool.workflow.createFailed': '创建失败',
  'chat.tool.workflow.submitting': '提交结果中',
  'chat.tool.workflow.completed': '已完成',
  'chat.tool.workflow.amended': '已调整',
  'chat.tool.workflow.running': '运行中',
  'chat.tool.workflow.done': '已结束',
  'chat.quota.modelVeryLow': '模型额度不足 \$0%',
  'chat.quota.modelExhausted': '模型额度已用尽',
  'chat.quota.dailyExhausted': '今日额度已用尽',
  'chat.quota.resetAt': '重置时间 \$0',
  'chat.suggest.1': '总结这个项目的结构和入口',
  'chat.suggest.2': '找出仓库里的 lint 错误并修复',
  'chat.suggest.3': '为最近的改动补上单元测试',
  'chat.action.editResend': '编辑并重发',
  'chat.action.edit.title': '编辑消息',
  'chat.action.edit.failed': '编辑失败: \$0',
  'chat.action.retry': '重试本轮',
  'chat.action.retry.failed': '重试失败',
  'chat.action.fork': '分叉对话',
  'chat.action.fork.failed': '分叉失败',
  'chat.action.rewind': '回滚文件到此',
  'chat.action.rewind.title': '回滚文件？',
  'chat.action.rewind.body': '将把此消息之后产生的文件变更回滚，对话保留',
  'chat.action.rewind.confirm': '回滚',
  'chat.action.rewind.failed': '回滚失败',
  'chat.action.fileChanges': '查看文件变更',
  'chat.action.fileChanges.failed': '获取失败: \$0',
  'chat.diff.truncated': '…（diff 过长已截断）',
  // ---- task list (official mobile layout) ----
  'tasks.sectionTitle': '当前设备上的工作区和任务',
  'tasks.stats': '\$0 个工作区 · \$1 个任务',
  'tasks.collapseAll': '收起全部工作区',
  'tasks.tidy': '整理任务',
  'tasks.refreshAll': '刷新工作区和任务',
  'tasks.tidy.groupLabel': '整理任务',
  'tasks.tidy.group': '按工作区',
  'tasks.tidy.timeline': '按时间线',
  'tasks.tidy.sortLabel': '排序方式',
  'tasks.tidy.sort.created': '创建时间',
  'tasks.tidy.sort.updated': '更新时间',
  'tasks.timeline.today': '今天',
  'tasks.timeline.yesterday': '昨天',
  'tasks.timeline.daysAgo': '\$0 天前',
  'tasks.timeline.lastWeek': '上周',
  'tasks.timeline.earlier': '更早',
  'tasks.updatedAt': '更新于 \$0',
  'tasks.taskCount': '\$0 个任务',
  'tasks.local': '本地',
  'tasks.new': '新建任务',
  'tasks.banner.nativeOff': '原生列表未启用，可在设置中开启',
  'tasks.banner.kicked': '其他终端占用了此设备连接，可等待其退出后重试',
  'tasks.banner.connecting': '正在连接桌面端…',
  'tasks.banner.onlineTitle': 'ZCode 远程控制',
  'tasks.banner.onlineSubtitle': '已连接到当前桌面窗口',
  'tasks.banner.onlineDesc': '本次连接可以查看当前设备上已打开的项目、任务和会话；二维码失效后需要回到桌面端重新连接。',
  'tasks.paneHint': '选择左侧任务查看会话',
  'tasks.commandSearch': '搜索并执行当前工作区可用的命令',
  'tasks.commandSearch.empty': '没有匹配的命令',
  'tasks.pinned': '已置顶',
  'tasks.projects': '项目',
  'tasks.search': '搜索',
  'tasks.sidebar.new': '新建任务',
  'tasks.sidebar.plugins': '插件市场',
  'tasks.sidebar.pluginsHint': '插件的安装与管理在桌面端 ZCode 中进行；此处保持与网页版一致的入口。',
  'tasks.sidebar.filterSort': '筛选和排序',
  'tasks.sidebar.archive': '归档',
  'tasks.archive.empty': '没有归档的任务',
  'remote.error.title': '无法连接到桌面设备',
  'remote.error.hint': '请确认桌面 ZCode 已打开且网络可用',
  'remote.reload': '重新加载',
  'settings.title': '设置',
  'settings.appearance': '外观',
  'settings.theme': '主题',
  'settings.theme.dark': '深色',
  'settings.theme.light': '浅色',
  'settings.theme.system': '跟随系统',
  'settings.general': '通用',
  'settings.language': '语言',
  'settings.language.zh': '中文',
  'settings.language.en': 'English',
  'settings.nativeList': '原生任务列表',
  'settings.nativeListHint': '原生显示设备在线状态与任务列表；关闭后仅用网页版',
  'settings.data': '数据',
  'settings.usageStats': '使用统计',
  'settings.usageStatsHint': '仅保存在本机',
  'settings.about': '关于 ZLinker',
  'about.version': '版本',
  'about.github': 'GitHub 仓库',
  'about.licenses': '开源许可',
  'about.privacy': '隐私政策',
  'about.tos': '服务条款',
  'about.disclaimer': 'ZLinker 是非官方的社区客户端，与 Zhipu AI 及 ZCode 无关联。',
  'usage.title': '使用统计',
  'usage.summary.devices': '设备数',
  'usage.summary.opens': '累计打开',
  'usage.perDevice': '按设备',
  'usage.opens': '\$0 次',
  'usage.addedAt': '添加于 \$0',
  'usage.neverUsed': '从未使用',
  'tasks.menu.usage': '使用统计',
  'tasks.menu.providers': '模型设置',
  'usageRpc.title': '用量',
  'usageRpc.appUsage': '应用用量',
  'usageRpc.rangeAll': '全部',
  'usageRpc.appUsageHint': '基于本机会话历史估算',
  'usageRpc.appUsageEmpty': '该时间范围内暂无用量',
  'usageRpc.loadFailed': '加载失败: \$0',
  'usageRpc.remaining': '剩余额度',
  'usageRpc.remainingDetail': '剩余 \$0% · 重置时间 \$1',
  'usageRpc.limits': '配额限制',
  'usageRpc.subscription': '订阅',
  'usageRpc.product': '产品',
  'usageRpc.billing': '计费周期',
  'usageRpc.renew': '续费时间',
  'usageRpc.expire': '到期时间',
  'usageRpc.used': '用量 \$0',
  'usageRpc.left': '剩余 \$0',
  'usageRpc.resetAt': '重置 \$0',
  'deskSet.title': '桌面设置',
  'deskSet.loadFailed': '读取失败: \$0',
  'deskSet.saveFailed': '保存失败: \$0',
  'deskSet.interaction': '交互行为',
  'deskSet.interactionHint': '任务运行中发送后续消息的默认行为',
  'deskSet.interactionQueue': '排队',
  'deskSet.interactionQueueHint': '自动排队，当前回合结束后依次发送',
  'deskSet.interactionGuide': '引导',
  'deskSet.interactionGuideHint': '引导当前任务转向新目标',
  'deskSet.autoArchive': '自动归档旧任务',
  'deskSet.autoArchiveHint': '符合条件的已完成任务在保留期后自动归档',
  'deskSet.autoArchiveDays': '\$0 天',
  'providers.title': '模型设置',
  'providers.suggest': '获取端点建议并拉取模型列表',
  'providers.subtitle': '管理自定义模型供应商，配置后可在聊天时选择使用。',
  'providers.add': '添加',
  'providers.addTitle': '添加模型供应商',
  'providers.name': '名称',
  'providers.apiFormat': 'API 格式',
  'providers.apiKey': 'API Key（可选）',
  'providers.models': '模型 ID（逗号分隔）',
  'providers.modelsCount': '\$0 个模型',
  'providers.disabled': '停用: \$0',
  'providers.loadFailed': '加载失败: \$0',
  'providers.toggleFailed': '切换失败: \$0',
  'providers.deleteFailed': '删除失败: \$0',
  'providers.addFailed': '添加失败: \$0',
  'providers.added': '已添加供应商',
  'providers.deleteTitle': '删除模型供应商？',
  'providers.deleteBody': '将删除「\$0」',
  'sched.menu': '定时与自动化',
  'sched.title': '定时与自动化',
  'sched.section.server': '设备自动化',
  'sched.section.local': '本地定时发送',
  'sched.openAuto': '管理设备自动化',
  'sched.add': '新建定时消息',
  'sched.empty': '暂无定时消息',
  'sched.noDevices': '请先添加可用设备',
  'sched.created': '已创建定时消息',
  'sched.device': '设备',
  'sched.message': '消息内容',
  'sched.time': '发送时间',
  'sched.pending': '待发送',
  'sched.sent': '已发送',
  'sched.failed': '失败',
  'sched.hint': '到点时需保持 App 在前台，且开启「原生任务列表」',
  'tasks.menu.automations': '自动化',
  'auto.title': '自动化',
  'auto.subtitle': '创建定时任务，或排队在闲时算力空闲时后台执行。',
  'auto.add': '新建',
  'auto.create': '新建定时任务',
  'auto.edit': '编辑定时任务',
  'auto.createManually': '创建定时任务',
  'auto.empty': '还没有定时任务',
  'auto.empty.desc': '创建一个任务，按周期自动运行你的指令。',
  'auto.loading': '正在获取定时任务…',
  'auto.loadFailed': '加载失败: \$0',
  'auto.unavailable.title': '设备定时任务不可用',
  'auto.unavailable.body': '设备离线或协议握手未完成，可先用「本地定时发送」，设备恢复后再管理定时任务。',
  'auto.opFailed': '操作失败: \$0',
  'auto.error.create': '创建失败，请重试',
  'auto.error.update': '保存失败，请重试',
  'auto.error.toggle': '状态更新失败，请重试',
  'auto.error.delete': '删除失败，请重试',
  'auto.created': '已创建任务',
  'auto.saved': '已保存',
  'auto.deleted': '已删除',
  'auto.delete.title': '删除定时任务',
  'auto.delete.body': '确定删除“\$0”？此操作无法撤销。',
  'auto.enabled': '运行中',
  'auto.disabled': '已暂停',
  'auto.name': '任务标题',
  'auto.name.hint': '例如：每日站会摘要',
  'auto.prompt': '指令',
  'auto.prompt.hint': '每次运行时这个任务要做什么？',
  'auto.hint': '配置任务的执行时间、指令和运行方式。',
  'auto.trigger': '调度',
  'auto.trigger.cron': 'Cron',
  'auto.trigger.interval': '间隔重复',
  'auto.trigger.oneShot': '一次性延迟',
  'auto.cronExpr': 'Cron 表达式',
  'auto.cronHint': '5 段式，如 0 9 * * 1-5 表示工作日每天 9 点',
  'auto.interval': '间隔',
  'auto.intervalUnit.label': '单位',
  'auto.intervalUnit.minute': '分钟',
  'auto.intervalUnit.hour': '小时',
  'auto.intervalUnit.day': '天',
  'auto.intervalUnit.week': '周',
  'auto.intervalUnit.month': '月',
  'auto.intervalUnit.year': '年',
  'auto.recurring': '无限重复',
  'auto.recurring.hint': '关闭后，运行固定次数即停止。',
  'auto.maxRuns': '最大运行次数',
  'auto.maxRuns.hint': '例如：5',
  'auto.maxRunsN': '最多 \$0 次',
  'auto.delayMinutes': '延迟分钟数',
  'auto.delayHint': '从创建时起延迟执行，最长 1 年',
  'auto.model': '模型',
  'auto.model.default': '默认模型',
  'auto.mode': '模式（可选）',
  'auto.mode.default': '默认',
  'auto.thoughtLevel': '思考等级',
  'auto.thoughtLevel.default': '默认（不指定）',
  'form.options.unavailable': '暂时无法获取可选项',
  'auto.targetTask': '绑定任务 ID（可选）',
  'auto.advanced': '更多选项',
  'auto.cronAt': '按表达式 \$0',
  'auto.cron.daily': '每天 \$0',
  'auto.cron.weekdays': '每工作日 \$0',
  'auto.cron.weekly': '每周\$1 \$0',
  'auto.cron.monthly': '每月 \$1 号 \$0',
  'auto.weekday.1': '一',
  'auto.weekday.2': '二',
  'auto.weekday.3': '三',
  'auto.weekday.4': '四',
  'auto.weekday.5': '五',
  'auto.weekday.6': '六',
  'auto.weekday.0': '日',
  'auto.weekday.sep': '、',
  'auto.every': '每 \$0 \$1',
  'auto.once': '一次性 · \$0后',
  'auto.minutes': '\$0 分钟',
  'auto.hours': '\$0 小时',
  'auto.days': '\$0 天',
  'auto.lastRun': '上次运行 \$0',
  'auto.err.title': '请填写标题',
  'auto.err.prompt': '请填写指令',
  'auto.err.cron': '请填写 Cron 表达式',
  'auto.err.interval': '间隔需为正整数',
  'auto.err.delay': '延迟需在 1 分钟到 1 年之间',
  'tasks.menu.offPeak': '闲时任务',
  'op.title': '闲时任务',
  'op.subtitle': '算力富余时段免费执行 · Coding Plan',
  'op.hint': '配置任务指令及其在闲时的运行方式。',
  'op.add': '新建闲时任务',
  'op.submit': '创建闲时任务',
  'op.empty': '还没有闲时任务。创建一个，让它在算力空闲时免费执行。',
  'op.loading': '正在获取闲时任务…',
  'op.loadFailed': '加载失败: \$0',
  'op.unavailable.title': '闲时任务不可用',
  'op.unavailable.body': '设备离线或协议握手未完成，稍后再试。',
  'op.name': '任务标题',
  'op.name.hint': '例如：夜间重构',
  'op.prompt': '任务指令',
  'op.prompt.hint': '描述希望 ZCode 在后台完成的工作、预期结果和约束，例如整理本周代码改动并生成站会摘要…',
  'op.model': '模型',
  'op.earliestAt': '最早可用时段',
  'op.earliest.any': '不限，排队后尽快',
  'op.keepAwake': '保持唤醒',
  'op.keepAwakeHint': '保持与设备的连接，以便及时收到结果',
  'op.permission': '权限模式',
  'op.permission.build': '变更前确认',
  'op.permission.plan': '计划模式',
  'op.permission.yolo': '完全访问',
  'op.permissionWarning': '闲时执行时无人值守，需要确认的操作会暂停任务直到你响应。',
  'op.fullAccessHint': '建议权限切换为完全访问，以减少任务失败率',
  'op.tpl.ci.title': 'CI 失败与不稳定测试报告',
  'op.tpl.ci.prompt': '扫描最近的 CI 运行，列出失败和不稳定测试及其可能原因，并按影响范围给出修复建议。',
  'op.tpl.docs.title': '文档同步检查',
  'op.tpl.docs.prompt':
      '基于当前代码实现和最近提交，检查仓库中的 README、docs、配置说明与使用示例是否过时或与实现不一致。仅修改能够从代码、配置或提交记录中直接确认的内容；不要猜测未验证的行为，并保持现有文档的结构、术语和写作风格。完成后列出修改的文件及每项修改依据；若无需修改，说明已检查的范围、证据与结论。',
  'op.tpl.standup.title': 'Git 站会摘要',
  'op.tpl.standup.prompt': '汇总本周 Git 活动，生成周五站会摘要：列出重要提交、已合并 PR 及主要变更，并保持简洁。',
  'op.created': '已提交闲时任务',
  'op.quota': '剩余额度 \$0',
  'op.earliest': '最早可用 \$0',
  'op.minutes': '\$0 分钟',
  'op.hours': '\$0 小时',
  'op.duration': '用时 \$0',
  'op.queue': '排队第 \$0 位',
  'op.status.queued': '等待闲时算力',
  'op.status.running': '运行中',
  'op.status.paused': '已暂停',
  'op.status.completed': '已完成',
  'op.status.failed': '失败',
  'op.status.cancelled': '已取消',
  'op.viewResult': '打开会话',
  'op.cancel': '取消任务',
  'op.cancel.title': '取消闲时任务？',
  'op.cancel.body': '「\$0」将停止执行，已修改的文件会保留。',
  'op.cancel.confirm': '取消任务',
  'op.deleteTitle': '删除此闲时任务？',
  'op.deleteBody': '此操作无法撤销。如果任务当前正在排队或运行中，将立即停止。',
  'op.delete.confirm': '删除闲时任务',
  'op.section.active': '进行中',
  'op.section.history': '历史',
  'op.err.prompt': '请填写指令',
  'op.err.noWorkspace': '该设备没有打开的工作区',
  'op.err.codingPlanOnly': '闲时任务仅向 Coding Plan 订阅用户开放',
  'op.err.quota': '闲时任务额度已用完，请稍后再试',
  'op.err.unavailable': '闲时任务服务暂时不可用，请稍后重试',
  'op.err.other': '闲时任务操作失败: \$0',
  'settings.notifications': '通知',
  'settings.notificationsHint': '任务完成/失败、闲时结果与自动化触发推送到本机',
  'settings.notify.tasks': '任务事件',
  'settings.notify.offPeak': '闲时事件',
  'settings.notify.auto': '自动化结果',
  'notify.task.done': '任务完成',
  'notify.task.failed': '任务失败',
  'notify.task.interrupted': '任务已中断',
  'notify.offPeak.done': '闲时任务完成',
  'notify.offPeak.failed': '闲时任务失败',
  'notify.auto.done': '自动化触发成功',
  'notify.auto.failed': '自动化触发失败',
  'settings.checkUpdate': '检查更新',
  'update.latest': '已是最新版本',
  'update.newVersion': '发现新版本 v\$0',
  'update.availableBody': '有新的 ZLinker 版本可用。',
  'update.download': '到浏览器下载',
  'update.later': '稍后',
  'update.failed': '检查更新失败: \$0',
  'update.storePending': '请通过 App Store 检查更新',

  // ---- Off-peak functional alignment (official desktop dictionary) ----
  'op.tab.settings': '设置',
  'op.tab.history': '历史',
  'op.history.empty': '还没有历史记录。',
  'op.history.delete': '删除历史记录',
  'op.badge.paused': '#\$0 已暂停',
  'op.pauseHint': '暂停时长超过队列等待时限的任务，将会被重新放回队列。',
  'op.continueHint': '票已失效时，「继续」会把任务重新排到队尾。',
  'op.discard.title': '丢弃闲时任务的草稿？',
  'op.discard.body': '你对当前闲时任务的更改将会丢失。',
  'op.discard.confirm': '丢弃',
  'op.banner': '订阅用户新功能体验：创建“闲时任务”，我们将免费在算力富余时段为你完成指派任务。',
  'op.edit': '编辑闲时任务',
  'op.edit.hint': '调整任务指令及其在闲时的运行方式。',
  'op.edit.save': '保存',
  'op.edit.menu': '编辑',
  'op.peakWarning': '此任务会在高峰时段运行，可能导致执行出错。',
  'op.limitReachedAt': '闲时任务额度已用完，可在\$0后再次创建。',
  'op.thought': '思考等级',
  'op.thought.default': '默认（不指定）',
  'op.remaining.min': '\$0 分钟',
  'op.remaining.hoursMin': '\$0 小时 \$1 分钟',

  // ---- Automations functional alignment (official desktop dictionary) ----
  'auto.preset': '调度方式',
  'auto.freq.hourly': '每小时',
  'auto.freq.daily': '每天',
  'auto.freq.weekdays': '每工作日',
  'auto.freq.weekly': '每周',
  'auto.freq.monthly': '每月',
  'auto.freq.customInterval': '自定义…',
  'auto.time': '时间',
  'auto.weekdayPick': '选择星期',
  'auto.monthDay': '几号',
  'auto.custom.title': '自定义重复',
  'auto.custom.everyN': '每 \$0 \$1',
  'auto.custom.ends': '结束',
  'auto.custom.never': '永不结束',
  'auto.custom.until': '指定日期',
  'auto.custom.dateLabel': '选择结束日期',
  'auto.custom.estRuns': '按估算将运行约 \$0 次后停止',
  'auto.schedule.preview': '运行时间：\$0',
  'auto.nextRun': '下次运行 \$0',
  'auto.runCount': '已运行 \$0 次',
  'auto.runCountLimited': '已运行 \$0/\$1 次',
  'auto.runNow': '立即运行',
  'auto.runNowQueued': '已触发，即将运行',
  'auto.runNowDuplicate': '上一条正在运行中，请稍后再试',
  'auto.runNowFailed': '触发运行失败',
  'auto.templates': '定时任务模板',
  'auto.tpl.pick': '选用模板',
  'auto.tpl.weeklyReview.title': '每周回顾',
  'auto.tpl.weeklyReview.desc': '每周五总结这一周发生的事情。',
  'auto.tpl.weeklyReview.prompt':
      '基于当前项目中可验证的活动生成精简周五回顾，汇总本周变更和待跟进事项；无法获取的信息明确标注，不修改代码或外部状态。',
  'auto.tpl.weeklyReview.schedule': '每周五 16:00',
  'auto.tpl.meetingPrep.title': '会议准备',
  'auto.tpl.meetingPrep.desc': '每周五总结这一周发生的事情。',
  'auto.tpl.meetingPrep.prompt':
      '基于可用的日历和项目信息生成精简会议简报，覆盖参会人、背景和议程；无法获取的信息明确标注，不修改外部状态。',
  'auto.tpl.meetingPrep.schedule': '每周五 16:00',
  'auto.tpl.contentIdeas.title': '内容灵感',
  'auto.tpl.contentIdeas.desc': '每周根据行业最新动态，草拟几条选题灵感。',
  'auto.tpl.contentIdeas.prompt':
      '基于可验证的近期行业和项目信息草拟几条内容灵感，注明使用的事实依据；无法获取的信息明确标注，不发布内容或修改外部状态。',
  'auto.tpl.contentIdeas.schedule': '每周一 9:00',
};

const _en = {
  'app.title': 'ZLinker',
  'devices.empty.title': 'No devices yet',
  'devices.empty.body':
      'Open "Remote Control" in ZCode desktop,\nthen scan or paste the link',
  'devices.add': 'Add device',
  'devices.add.scan': 'Scan QR code',
  'devices.add.scanHint': 'Aim at the ZCode remote-control QR code',
  'devices.add.paste': 'Paste link',
  'devices.add.pasteHint': 'Paste the remote-control URL',
  'devices.add.pasteTitle': 'Paste link',
  'devices.add.pasteHint2':
      'https://zcode.z.ai/remote/v4?sid=...&hash=...&t=...',
  'devices.add.cancel': 'Cancel',
  'devices.add.confirm': 'Add',
  'devices.add.savedUnparsed': 'URL could not be parsed but was saved',
  'devices.scan.title': 'Scan to add device',
  'devices.scan.fromGallery': 'Pick a QR image from gallery',
  'devices.scan.cameraError':
      'Camera unavailable: \$0\nUse "pick from gallery" in the top-right instead',
  'devices.scan.cameraInitFailed': 'Camera failed to start',
  'devices.scan.decodeFailed': 'No QR code found in that image',
  'devices.scan.decodeError': 'Image decode failed: \$0',
  'devices.scan.hint':
      'Aim at the ZCode remote-control QR code, or pick a screenshot',
  'devices.lastUsed': 'Last used \$0',
  'devices.neverUsed': 'Never used',
  'devices.menu.rename': 'Rename',
  'devices.menu.pin': 'Pin',
  'devices.menu.unpin': 'Unpin',
  'devices.menu.web': 'Open web version',
  'devices.menu.browser': 'Open in browser',
  'devices.menu.copy': 'Copy link',
  'devices.menu.delete': 'Delete',
  'devices.clipboard.offer':
      'A remote-control link is on the clipboard — add it?',
  'devices.clipboard.add': 'Add',
  'devices.menu.export': 'Export device backup',
  'devices.menu.import': 'Import device backup',
  'devices.rename.title': 'Rename device',
  'devices.rename.hint': 'Device name',
  'devices.rename.save': 'Save',
  'devices.delete.title': 'Delete device',
  'devices.delete.body': 'Delete "\$0"?',
  'devices.delete.confirm': 'Delete',
  'devices.copy.done': 'Link copied',
  'devices.export.done': 'Device backup JSON copied to clipboard',
  'devices.import.title': 'Import devices',
  'devices.import.hint': 'Paste device backup JSON',
  'devices.import.confirm': 'Import',
  'devices.import.done': 'Imported \$0 device(s)',
  'devices.import.invalid': 'Invalid backup format',
  'devices.unnamed': 'Unnamed device',
  'status.online': 'Online',
  'status.connecting': 'Connecting…',
  'status.offline': 'Offline',
  'status.error': 'Native list unavailable — use the web version',
  'status.kicked': 'Taken over by another terminal',
  'status.tasksRunning': '\$0 task(s) running',
  'time.justNow': 'just now',
  'time.minutesAgo': '\$0 min ago',
  'time.hoursAgo': '\$0 h ago',
  'time.daysAgo': '\$0 d ago',
  'time.minutesLater': 'in \$0 min',
  'time.hoursLater': 'in \$0 h',
  'time.daysLater': 'in \$0 d',
  'time.short.justNow': 'now',
  'time.short.minutes': '\$0m',
  'time.short.hours': '\$0h',
  'time.short.days': '\$0d',
  'tasks.title': 'Tasks',
  'tasks.empty': 'No tasks yet',
  'tasks.loading': 'Loading tasks…',
  'tasks.fallback.title': 'Native list unavailable',
  'tasks.fallback.body':
      'The protocol link is not ready — use the web version for now.',
  'tasks.openWeb': 'Open web version',
  'tasks.retry': 'Retry',
  'tasks.stop': 'Stop',
  'tasks.pause': 'Pause',
  'tasks.resume': 'Resume',
  'tasks.opFailed': 'Operation failed: \$0',
  'tasks.untitled': 'Untitled task',
  'tasks.workspaces': 'Workspace',
  'tasks.pickWorkspace': 'Choose a workspace',
  'tasks.noWorkspaces.title': 'No open workspace on the desktop',
  'tasks.noWorkspaces.body':
      'Open a project in ZCode desktop first, then retry here',
  'tasks.deepLinking': 'Jumping to the task…',
  'phase.running': 'Running',
  'phase.prewarming': 'Prewarming',
  'phase.completedSuccess': 'Completed',
  'phase.completedInterrupted': 'Interrupted',
  'phase.error': 'Error',
  'phase.draft': 'Draft',
  'phase.paused': 'Paused',
  'phase.idle': 'Idle',
  // ---- task actions & tags (web taskList/task-item menu parity) ----
  'tasks.awaiting': 'Awaiting confirmation',
  'tasks.renamePlaceholder': 'Task name',
  'tasks.action.pin': 'Pin',
  'tasks.action.unpin': 'Unpin',
  'tasks.action.rename': 'Rename',
  'tasks.action.archive': 'Archive',
  'tasks.action.unarchive': 'Unarchive',
  'tasks.action.archiveView': 'View archive',
  'tasks.action.unarchiveView': 'Exit archive view',
  'tasks.action.markUnread': 'Mark as unread',
  'tasks.action.markRead': 'Mark as read',
  'tasks.action.delete': 'Delete',
  'tasks.action.deleteTitle': 'Delete this task?',
  'tasks.action.deleteDesc':
      'Task "\$0" will be removed from the workspace. Existing records cannot be recovered.',
  'tasks.workspaceKind.local': 'Local',
  'tasks.workspaceKind.conversation': 'Conversation',
  'tasks.workspaceKind.remote': 'Remote',
  'common.cancel': 'Cancel',
  'common.retryLater': 'Retry later',
  'common.save': 'Save',
  // ---- webRemoteControl failure states (official copy) ----
  'remote.failure.session-not-found':
      'This Web remote control link is no longer valid. Start it again from desktop.',
  'remote.failure.session-expired':
      'This Web remote control session has already ended. Generate a new link from desktop to continue.',
  'remote.failure.session-conflict':
      'This link is already being used by another page. Close the other page and scan again.',
  'remote.failure.kicked':
      'The relay kicked this pairing. Close the other page and generate a new QR code from desktop.',
  'remote.failure.workspace-closed':
      'The shared desktop window has been closed. Go back to desktop and start Web remote control again.',
  'remote.failure.desktop-disconnected':
      'The desktop side disconnected, so this Web remote control session can no longer continue.',
  'remote.failure.invalid-mobile-connection':
      'The current mobile connection is no longer valid. Reload the page and reconnect.',
  'remote.failure.desktop-bootstrap-timeout':
      'The desktop window did not respond in time. Make sure it is still running, then reload.',
  'remote.failure.connection-recovery-timeout':
      'The mobile connection did not recover in time, so Web remote control cannot keep syncing yet.',
  'remote.failure.relay-unavailable':
      'The external relay connection is unavailable. Make sure desktop is online, then try again.',
  'remote.failure.unsupported-action':
      'Web remote control mode can only open workspaces that are already open in the current desktop window.',
  'remote.failure.unexpected-error':
      'Could not start mobile remote control. Try again from desktop.',
  // ---- chat (native conversation) ----
  'chat.appBar': 'Task session',
  'chat.copy': 'Copy',
  'chat.copied': 'Copied',
  'chat.expand': 'Expand',
  'chat.collapse': 'Collapse',
  'chat.empty': 'No messages yet',
  'chat.draftHint': 'Type a message to start a new task',
  'chat.noSession': 'No session yet',
  'chat.noOlder': 'No older messages',
  'chat.loadOlder.stale': 'Session data was refreshed — try again',
  'chat.loadOlder': 'Load older messages',
  'chat.loadOlder.failed': 'Load failed: \$0',
  'chat.subscribe.failed': 'Subscribe failed: \$0',
  'chat.reconnecting': 'Connection lost, reconnecting…',
  'chat.kicked.title': 'Taken over by another device',
  'chat.kicked.body':
      'Only one terminal may follow a task at a time. Reconnect after the other device exits.',
  'chat.kicked.reconnect': 'Reconnect',
  'chat.creating': 'Creating the session (first run may warm up)…',
  'chat.send.failed': 'Send failed: \$0',
  'chat.op.failed': 'Operation failed: \$0',
  'chat.compact.failed': 'Compact failed',
  'chat.goal.pauseFailed': 'Pause goal failed',
  'chat.goal.resumeFailed': 'Resume goal failed',
  'chat.held.title': 'Queued messages pending',
  'chat.held.body':
      'Sending now clears the queued messages and jumps the queue',
  'chat.held.keep': 'Send to queue',
  'chat.held.clear': 'Send now',
  'chat.reasoning': 'Reasoning',
  'chat.reasoning.thinking': 'Thinking…',
  'chat.turn.worked': 'Worked \$0',
  'chat.time.secOnly': '\$0s',
  'chat.time.minSec': '\$0m \$1s',
  'chat.files.changed': '\$0 files changed',
  'chat.files.undo': 'Undo',
  'chat.subagent': 'Subagent · \$0',
  'chat.bgWorks': '\$0 background tasks running: \$1',
  'chat.tool.input': 'Input',
  'chat.tool.output': 'Output',
  'chat.tool.error': 'Error',
  'chat.tool.wrote': 'Wrote \$0',
  'chat.tool.terminal': 'Terminal',
  'chat.tool.explore': 'Explore',
  'chat.tool.exploreN': 'Explore · \$0 files',
  'chat.marker.compact': 'Compacted · \$0\$1',
  'chat.marker.tokens': ' · \$0→\$1 tokens',
  'chat.marker.forkNotice': 'Forked from a session',
  'chat.marker.forkCreated': 'Fork session created',
  'chat.marker.modelChange': 'Model switched \$0 → \$1',
  'chat.marker.goalSet': 'Goal set: \$0',
  'chat.marker.goalVerify': 'Goal verify round \$0 · \$1',
  'chat.marker.retryNotice': 'Auto retry #\$0 (\$1)',
  'chat.marker.checkpointRestored': 'Checkpoint restored',
  'chat.queue.count': 'Queued \$0',
  'chat.tool.askQuestion.asking': 'Asking questions',
  'chat.tool.askQuestion.asked': 'Asked',
  'chat.tool.askQuestion.askedN': 'Asked · \$0 questions',
  'chat.tool.askQuestion.autoContinued': 'No answer; continued automatically',
  'chat.tool.taskOutput.kind': 'Task output',
  'chat.tool.taskOutput.fetching': 'Fetching task output',
  'chat.tool.taskOutput.running': 'Task running',
  'chat.tool.taskOutput.failed': 'Failed to fetch output',
  'chat.tool.taskOutput.denied': 'Fetch denied',
  'chat.tool.taskOutput.stopped': 'Fetch stopped',
  'chat.tool.taskOutput.retrieved': 'Retrieved',
  'chat.tool.taskStop.kind': 'Stop task',
  'chat.tool.taskStop.stopping': 'Stopping task',
  'chat.tool.taskStop.failed': 'Failed to stop task',
  'chat.tool.taskStop.denied': 'Stop denied',
  'chat.tool.taskStop.cancelled': 'Stop cancelled',
  'chat.tool.taskStop.stopped': 'Stopped',
  'chat.tool.send.kind': 'Send message',
  'chat.tool.send.sending': 'Sending',
  'chat.tool.send.sent': 'Sent',
  'chat.tool.send.failed': 'Send failed',
  'chat.tool.send.denied': 'Send denied',
  'chat.tool.send.stopped': 'Send stopped',
  'chat.tool.group.terminal': 'Terminal',
  'chat.tool.group.count': '\$0 commands',
  'chat.tool.group.failed': '\$0 failed',
  'chat.tool.group.stopped': '\$0 stopped',
  'chat.mention.title': 'Mention',
  'chat.mention.selectItem': 'Pick a reference to insert into the composer',
  'chat.mention.searchHint': 'Type to search files, skills or sessions',
  'chat.mention.emptyResults': 'No matching mentions',
  'chat.mention.category.files': 'Files',
  'chat.mention.category.files.description': 'Search workspace files and insert a reference',
  'chat.mention.category.skills': 'Skills',
  'chat.mention.category.skills.description': 'Insert a skill reference',
  'chat.mention.category.subagents': 'Subagents',
  'chat.mention.category.subagents.description': 'Insert a subagent reference',
  'chat.mention.category.sessions': 'Sessions',
  'chat.mention.category.sessions.description': 'Insert a session reference',
  'goalPanel.title': 'Goal',
  'goalPanel.completedN': '\$0 completed',
  'goalPanel.duration.s': '\$0s',
  'goalPanel.duration.ms': '\$0m \$1s',
  'goalPanel.runningFor': 'running for \$0m \$1s',
  'goalPanel.agents': 'Agents',
  'goalPanel.agentsRunning': '\$0 running',
  'chat.queue.autoOn': 'Auto-send: on',
  'chat.queue.moveUp': 'Move up',
  'chat.queue.moveDown': 'Move down',
  'chat.interact.snooze': 'Auto-continue later',
  'chat.bgWorks.cancel': 'Cancel this background work',
  'chat.rewind.checking': 'Checking rewritable files…',
  'chat.rewind.safeTitle': 'These files can be safely rewound',
  'chat.rewind.unsafeTitle': 'Some files cannot be safely rewound',
  'chat.rewind.cannotApply': 'Some files cannot be safely rewound. No files were written.',
  'chat.rewind.confirm': 'Rewind changes',
  'chat.queue.autoOff': 'Auto-send: off',
  'chat.queue.sendNow': 'Send now',
  'chat.queue.edit': 'Edit',
  'chat.queue.edit.title': 'Edit queued message',
  'chat.queue.delete.title': 'Delete queued message?',
  'chat.interact.permission': 'Permission · \$0',
  'chat.interact.waiting': 'Waiting for your input',
  'chat.interact.hint': 'Type a reply…',
  'chat.interact.allowOnce': 'Allow once',
  'chat.interact.allowAlways': 'Always allow',
  'chat.interact.deny': 'Deny',
  'chat.interact.custom': 'Custom',
  'chat.interact.pick': 'Pick',
  'chat.interact.submit': 'Submit',
  'chat.interact.plan.title': 'Plan approval',
  'chat.interact.plan.viewPlan': 'View plan',
  'chat.interact.plan.feedback': 'Feedback (optional, used as the decline reason)',
  'chat.interact.plan.approve': 'Approve & continue',
  'chat.interact.plan.decline': 'Decline',
  'chat.interact.form.submit': 'Submit answers',
  'chat.interact.form.cancel': 'Cancel',
  'chat.interact.form.custom': 'Custom answer…',
  'chat.interact.form.multi': 'multi-select',
  'chat.interact.hook.title': 'Workspace hook review',
  'chat.interact.hook.warning': 'These hooks come from the workspace and may execute code',
  'chat.interact.hook.trust': 'Trust selected hooks',
  'chat.interact.hook.empty': 'No hooks to review',
  'chat.mode.build': 'Confirm changes',
  'chat.mode.build.desc': 'Ask me before editing files.',
  'chat.mode.edit': 'Auto edit',
  'chat.mode.edit.desc': 'Edits files automatically.',
  'chat.mode.plan': 'Plan mode',
  'chat.mode.plan.desc': 'Plans before editing.',
  'chat.mode.yolo': 'Full access',
  'chat.mode.yolo.desc': 'Fewer confirmations.',
  'chat.followup.queue': 'Queue',
  'chat.followup.guide': 'Guide',
  'chat.sheet.title': 'Model & mode',
  'chat.sheet.draftTitle': 'New task · model & mode',
  'chat.sheet.currentModel': 'Current model: \$0',
  'chat.sheet.thought': 'Thought level',
  'chat.sheet.mode': 'Collaboration mode',
  'chat.sheet.followup': 'Follow-up messages',
  'chat.sheet.other': 'Other settings',
  'chat.sheet.rejected': 'Rejected: \$0',
  'chat.usage.context': 'Context',
  'chat.usage.input': 'Total input',
  'chat.usage.output': 'Total output',
  'chat.usage.cacheRead': 'Cache read',
  'chat.usage.cacheWrite': 'Cache write',
  'chat.json.empty': '(no data)',
  'chat.slash.empty': 'No matching commands',
  'chat.skills.title': 'Pick skills',
  'chat.skills.empty': 'No skills available',
  'chat.input.hint': 'Describe the next change',
  'chat.input.attach': 'Add context',
  'chat.input.skills': 'Pick a skill',
  'chat.attach.pickFailed': 'File picking failed: \$0',
  'chat.attach.uploading': 'Uploading attachments…',
  'chat.attach.loadFailed': '[image failed to load] \$0',
  'chat.more': 'More',
  'chat.more.rename': 'Rename task',
  'chat.more.rename.hint': 'Task name',
  'chat.more.rename.save': 'Save',
  'chat.more.pin': 'Pin task',
  'chat.more.unpin': 'Unpin task',
  'chat.more.archive': 'Archive task',
  'chat.more.unread': 'Mark as unread',
  'chat.more.copyPath': 'Copy path',
  'chat.more.copyId': 'Copy session ID',
  'chat.more.copyLink': 'Copy task link',
  'chat.more.linkCopied': 'Task link copied',
  'chat.more.idCopied': 'Task ID copied',
  'chat.more.pathCopied': 'Path copied',
  'chat.more.noPath': 'No workspace path available',
  'chat.more.noLink': 'No task link available',
  'chat.more.compact': 'Compact context',
  'chat.more.usage': 'Usage',
  'chat.more.plans': 'Plans',
  'chat.plans': 'Plans',
  'chat.plans.failed': 'Failed to load plans: \$0',
  'chat.plans.current': 'Current plan',
  'chat.plans.history': 'Plan history',
  'chat.plans.empty': 'No plans yet',
  'chat.plans.planN': 'Plan \$0',
  'chat.files.reverted': 'This turn has been reverted',
  'chat.rewind.done': 'Rewound to before this turn',
  'chat.status.gitDirty': '\$0 uncommitted files',
  'chat.status.section.workflows': 'Workflows',
  'chat.statusPanel.todo': 'To-do',
  'chat.status.section.terminals': 'Terminals',
  'chat.status.section.runningCount': '\$0 background runs',
  'chat.status.workflowUnnamed': 'Workflow script',
  'chat.status.workflowSteps': '\$0/\$1 steps',
  'chat.workflow.status.pending': 'Pending',
  'chat.workflow.status.running': 'Running',
  'chat.workflow.status.completed': 'Completed',
  'chat.workflow.status.errored': 'Errored',
  'chat.workflow.status.stopped': 'Stopped',
  'chat.status.bash': 'Terminal',
  'chat.search.tooltip': 'Search',
  'chat.search.hint': 'Search messages',
  'chat.search.count': '\$0/\$1',
  'chat.search.none': 'No results',
  'chat.search.prev': 'Previous match',
  'chat.search.next': 'Next match',
  'chat.history.tooltip': 'Input history',
  'chat.history.title': 'Recent prompts',
  'chat.history.empty': 'No input history yet',
  'chat.more.export': 'Export Markdown',
  'chat.export.title': 'Export conversation',
  'chat.export.copy': 'Copy all',
  'chat.export.save': 'Save as .md file',
  'chat.export.saved': 'Markdown file saved',
  'chat.export.failed': 'Export failed: \$0',
  'chat.export.role.user': 'User',
  'chat.export.role.assistant': 'Assistant',
  'chat.tool.cua.kind': 'Computer use',
  'chat.tool.cua.done': 'done',
  'chat.tool.cua.failed': 'failed',
  'chat.tool.cron.kind': 'Scheduled automation',
  'chat.tool.cron.updated': 'Updated automation',
  'chat.tool.cron.offpeak': 'Off-peak task',
  'chat.tool.workflow.kind': 'Workflow',
  'chat.workflow.card.kindWriting': 'Writing workflow',
  'chat.workflow.card.kindRan': 'Workflow',
  'chat.workflow.card.kindAmendWriting': 'Amending workflow',
  'chat.workflow.card.kindAmendRan': 'Workflow amendment',
  'chat.workflow.card.created': 'Compiled',
  'chat.workflow.card.createFailed': 'Compile failed',
  'chat.workflow.card.phases': '\$0 phases',
  'chat.workflow.card.agents': '\$0 agents',
  'chat.workflow.card.working': '\$0 working',
  'chat.workflow.card.diagnostics': '\$0 more diagnostics',
  'chat.workflow.card.unphased': 'Unphased',
  'chat.workflow.card.artifactsMore': '\$0 more artifacts',
  'chat.workflow.stop.user': 'stopped manually',
  'chat.workflow.stop.model': 'stopped by model',
  'chat.workflow.stop.provider': 'stopped by provider',
  'chat.workflow.stop.interrupted': 'interrupted',
  'chat.workflow.stop.superseded': 'superseded',
  'chat.workflow.run.resumable': 'resumable',
  'chat.workflow.actorNotStarted': 'This subagent has not started yet',
  'wrp.title': 'Run details',
  'wrp.fallbackName': 'Workflow script',
  'wrp.stop': 'Stop run',
  'wrp.resume': 'Resume run',
  'wrp.usage': 'Usage: \$0 tokens · \$1 steps',
  'wrp.lineage': 'amended from \$0',
  'wrp.phases': 'Phases',
  'wrp.artifacts': 'Artifacts',
  'wrp.artifacts.empty': 'This run published no artifacts',
  'wrp.artifacts.items': '\$0 items',
  'wrp.questions': 'Questions',
  'wrp.action.rejected': 'Action rejected: \$0',
  'chat.workflow.card.noAgents': 'No agents',
  'chat.tool.workflow.creating': 'creating',
  'chat.tool.workflow.created': 'created',
  'chat.tool.workflow.createFailed': 'create failed',
  'chat.tool.workflow.submitting': 'submitting result',
  'chat.tool.workflow.completed': 'completed',
  'chat.tool.workflow.amended': 'amended',
  'chat.tool.workflow.running': 'running',
  'chat.tool.workflow.done': 'finished',
  'chat.quota.modelVeryLow': 'Model quota below \$0%',
  'chat.quota.modelExhausted': 'Model quota exhausted',
  'chat.quota.dailyExhausted': 'Daily quota exhausted',
  'chat.quota.resetAt': 'resets \$0',
  'chat.suggest.1': 'Summarize this project and its entry points',
  'chat.suggest.2': 'Find and fix lint errors in the repo',
  'chat.suggest.3': 'Add unit tests for the latest changes',
  'chat.action.editResend': 'Edit & resend',
  'chat.action.edit.title': 'Edit message',
  'chat.action.edit.failed': 'Edit failed: \$0',
  'chat.action.retry': 'Retry turn',
  'chat.action.retry.failed': 'Retry failed',
  'chat.action.fork': 'Fork conversation',
  'chat.action.fork.failed': 'Fork failed',
  'chat.action.rewind': 'Rewind files here',
  'chat.action.rewind.title': 'Rewind files?',
  'chat.action.rewind.body':
      'File changes made after this message will be rolled back; the conversation is kept',
  'chat.action.rewind.confirm': 'Rewind',
  'chat.action.rewind.failed': 'Rewind failed',
  'chat.action.fileChanges': 'View file changes',
  'chat.action.fileChanges.failed': 'Failed to load: \$0',
  'chat.diff.truncated': '… (diff truncated)',
  // ---- task list (official mobile layout) ----
  'tasks.sectionTitle': 'Workspaces & tasks on this device',
  'tasks.stats': '\$0 workspaces · \$1 tasks',
  'tasks.collapseAll': 'Collapse all workspaces',
  'tasks.tidy': 'Tidy tasks',
  'tasks.refreshAll': 'Refresh workspaces & tasks',
  'tasks.tidy.groupLabel': 'Tidy tasks',
  'tasks.tidy.group': 'By workspace',
  'tasks.tidy.timeline': 'By timeline',
  'tasks.tidy.sortLabel': 'Sort by',
  'tasks.tidy.sort.created': 'Created time',
  'tasks.tidy.sort.updated': 'Updated time',
  'tasks.timeline.today': 'Today',
  'tasks.timeline.yesterday': 'Yesterday',
  'tasks.timeline.daysAgo': '\$0 days ago',
  'tasks.timeline.lastWeek': 'Last week',
  'tasks.timeline.earlier': 'Earlier',
  'tasks.updatedAt': 'Updated \$0',
  'tasks.taskCount': '\$0 tasks',
  'tasks.local': 'Local',
  'tasks.new': 'New task',
  'tasks.banner.nativeOff': 'The native list is off; enable it in settings',
  'tasks.banner.kicked':
      'Another terminal holds this device connection; retry after it exits',
  'tasks.banner.connecting': 'Connecting to the desktop…',
  'tasks.banner.onlineTitle': 'ZCode Remote Control',
  'tasks.banner.onlineSubtitle': 'Connected to the current desktop window',
  'tasks.banner.onlineDesc':
      'This connection can view the projects, tasks and sessions open on this device. After the QR code expires, reconnect from the desktop app.',
  'tasks.paneHint': 'Pick a task on the left to view its session',
  'tasks.commandSearch': 'Search and run commands available in this workspace',
  'tasks.commandSearch.empty': 'No matching commands',
  'tasks.pinned': 'Pinned',
  'tasks.projects': 'Projects',
  'tasks.search': 'Search',
  'tasks.sidebar.new': 'New task',
  'tasks.sidebar.plugins': 'Plugins',
  'tasks.sidebar.pluginsHint':
      'Plugins are installed and managed in the ZCode desktop app; this entry mirrors the web sidebar.',
  'tasks.sidebar.filterSort': 'Filter & sort',
  'tasks.sidebar.archive': 'Archive',
  'tasks.archive.empty': 'No archived tasks',
  'remote.error.title': 'Cannot reach the desktop device',
  'remote.error.hint':
      'Make sure ZCode desktop is running and the network works',
  'remote.reload': 'Reload',
  'settings.title': 'Settings',
  'settings.appearance': 'Appearance',
  'settings.theme': 'Theme',
  'settings.theme.dark': 'Dark',
  'settings.theme.light': 'Light',
  'settings.theme.system': 'System',
  'settings.general': 'General',
  'settings.language': 'Language',
  'settings.language.zh': '中文',
  'settings.language.en': 'English',
  'settings.nativeList': 'Native task list',
  'settings.nativeListHint':
      'Native device status and task list; turn off to use the web version only',
  'settings.data': 'Data',
  'settings.usageStats': 'Usage statistics',
  'settings.usageStatsHint': 'Stored on this device only',
  'settings.about': 'About ZLinker',
  'about.version': 'Version',
  'about.github': 'GitHub repository',
  'about.licenses': 'Open-source licenses',
  'about.privacy': 'Privacy policy',
  'about.tos': 'Terms of Service',
  'about.disclaimer':
      'ZLinker is an unofficial community client, not affiliated with Zhipu AI or ZCode.',
  'usage.title': 'Usage statistics',
  'usage.summary.devices': 'Devices',
  'usage.summary.opens': 'Total opens',
  'usage.perDevice': 'Per device',
  'usage.opens': '\$0 opens',
  'usage.addedAt': 'Added \$0',
  'usage.neverUsed': 'Never used',
  'tasks.menu.usage': 'Usage stats',
  'tasks.menu.providers': 'Model settings',
  'usageRpc.title': 'Usage',
  'usageRpc.appUsage': 'App usage',
  'usageRpc.rangeAll': 'All',
  'usageRpc.appUsageHint': 'Estimated from local session history',
  'usageRpc.appUsageEmpty': 'No usage in this range',
  'usageRpc.loadFailed': 'Load failed: \$0',
  'usageRpc.remaining': 'Remaining quota',
  'usageRpc.remainingDetail': '\$0% left · resets \$1',
  'usageRpc.limits': 'Quota limits',
  'usageRpc.subscription': 'Subscription',
  'usageRpc.product': 'Product',
  'usageRpc.billing': 'Billing cycle',
  'usageRpc.renew': 'Renews',
  'usageRpc.expire': 'Expires',
  'usageRpc.used': 'Used \$0',
  'usageRpc.left': '\$0 left',
  'usageRpc.resetAt': 'Resets \$0',
  'deskSet.title': 'Desktop settings',
  'deskSet.loadFailed': 'Load failed: \$0',
  'deskSet.saveFailed': 'Save failed: \$0',
  'deskSet.interaction': 'Interaction behavior',
  'deskSet.interactionHint': 'Default behavior when sending a follow-up while a turn is running',
  'deskSet.interactionQueue': 'Queue',
  'deskSet.interactionQueueHint': 'Queue automatically, sent after the current turn ends',
  'deskSet.interactionGuide': 'Guide',
  'deskSet.interactionGuideHint': 'Steer the running task toward the new input',
  'deskSet.autoArchive': 'Auto-archive old tasks',
  'deskSet.autoArchiveHint': 'Archive eligible completed tasks after the retention window',
  'deskSet.autoArchiveDays': '\$0 days',
  'providers.title': 'Model settings',
  'providers.suggest': 'Suggest endpoints and fetch models',
  'providers.subtitle':
      'Manage custom model providers; once configured they are selectable in chats.',
  'providers.add': 'Add',
  'providers.addTitle': 'Add model provider',
  'providers.name': 'Name',
  'providers.apiFormat': 'API format',
  'providers.apiKey': 'API Key (optional)',
  'providers.models': 'Model IDs (comma-separated)',
  'providers.modelsCount': '\$0 models',
  'providers.disabled': 'Disabled: \$0',
  'providers.loadFailed': 'Load failed: \$0',
  'providers.toggleFailed': 'Toggle failed: \$0',
  'providers.deleteFailed': 'Delete failed: \$0',
  'providers.addFailed': 'Add failed: \$0',
  'providers.added': 'Provider added',
  'providers.deleteTitle': 'Delete model provider?',
  'providers.deleteBody': 'This deletes "\$0".',
  'sched.menu': 'Scheduled & automations',
  'sched.title': 'Scheduled & automations',
  'sched.section.server': 'Device automations',
  'sched.section.local': 'Local scheduled messages',
  'sched.openAuto': 'Manage device automations',
  'sched.add': 'New message',
  'sched.empty': 'No scheduled messages',
  'sched.noDevices': 'Add a device first',
  'sched.created': 'Scheduled message created',
  'sched.device': 'Device',
  'sched.message': 'Message',
  'sched.time': 'Send at',
  'sched.pending': 'Pending',
  'sched.sent': 'Sent',
  'sched.failed': 'Failed',
  'sched.hint':
      'Keep the app in the foreground at fire time, with the native task list enabled',
  'tasks.menu.automations': 'Automations',
  'auto.title': 'Automations',
  'auto.subtitle':
      'Create scheduled tasks, or queue runs for idle compute windows.',
  'auto.add': 'New',
  'auto.create': 'New scheduled task',
  'auto.edit': 'Edit scheduled task',
  'auto.createManually': 'Create scheduled task',
  'auto.empty': 'No scheduled tasks yet',
  'auto.empty.desc': 'Create a task to run your instructions on a schedule.',
  'auto.loading': 'Loading scheduled tasks…',
  'auto.loadFailed': 'Load failed: \$0',
  'auto.unavailable.title': 'Device scheduled tasks unavailable',
  'auto.unavailable.body':
      'The device is offline or the protocol handshake is unfinished. Use "local scheduled messages" as a fallback and manage automations once the device is back.',
  'auto.opFailed': 'Operation failed: \$0',
  'auto.error.create': 'Create failed, please retry',
  'auto.error.update': 'Save failed, please retry',
  'auto.error.toggle': 'Status update failed, please retry',
  'auto.error.delete': 'Delete failed, please retry',
  'auto.created': 'Task created',
  'auto.saved': 'Saved',
  'auto.deleted': 'Deleted',
  'auto.delete.title': 'Delete scheduled task',
  'auto.delete.body': 'Delete "\$0"? This cannot be undone.',
  'auto.enabled': 'Running',
  'auto.disabled': 'Paused',
  'auto.name': 'Task title',
  'auto.name.hint': 'e.g. Daily standup summary',
  'auto.prompt': 'Instructions',
  'auto.prompt.hint': 'What should this task do each time it runs?',
  'auto.hint': 'Configure the schedule, instructions and how it runs.',
  'auto.trigger': 'Schedule',
  'auto.trigger.cron': 'Cron',
  'auto.trigger.interval': 'Interval',
  'auto.trigger.oneShot': 'One-shot',
  'auto.cronExpr': 'Cron expression',
  'auto.cronHint': '5 fields, e.g. 0 9 * * 1-5 for weekdays at 9',
  'auto.interval': 'Every',
  'auto.intervalUnit.label': 'Unit',
  'auto.intervalUnit.minute': 'minute(s)',
  'auto.intervalUnit.hour': 'hour(s)',
  'auto.intervalUnit.day': 'day(s)',
  'auto.intervalUnit.week': 'week(s)',
  'auto.intervalUnit.month': 'month(s)',
  'auto.intervalUnit.year': 'year(s)',
  'auto.recurring': 'Repeat indefinitely',
  'auto.recurring.hint': 'Turn off to stop after a fixed number of runs.',
  'auto.maxRuns': 'Max runs',
  'auto.maxRuns.hint': 'e.g. 5',
  'auto.maxRunsN': 'max \$0 runs',
  'auto.delayMinutes': 'Delay (minutes)',
  'auto.delayHint': 'Delayed from creation, up to 1 year',
  'auto.model': 'Model',
  'auto.model.default': 'Default model',
  'auto.mode': 'Mode (optional)',
  'auto.mode.default': 'Default',
  'auto.thoughtLevel': 'Thought level',
  'auto.thoughtLevel.default': 'Default (unspecified)',
  'form.options.unavailable': 'Options unavailable right now',
  'auto.targetTask': 'Target task ID (optional)',
  'auto.advanced': 'More options',
  'auto.cronAt': 'Expression \$0',
  'auto.cron.daily': 'Daily at \$0',
  'auto.cron.weekdays': 'Weekdays at \$0',
  'auto.cron.weekly': 'Weekly on \$1 at \$0',
  'auto.cron.monthly': 'Monthly on day \$1 at \$0',
  'auto.weekday.1': 'Mon',
  'auto.weekday.2': 'Tue',
  'auto.weekday.3': 'Wed',
  'auto.weekday.4': 'Thu',
  'auto.weekday.5': 'Fri',
  'auto.weekday.6': 'Sat',
  'auto.weekday.0': 'Sun',
  'auto.weekday.sep': ', ',
  'auto.every': 'Every \$0 \$1',
  'auto.once': 'One-shot · after \$0',
  'auto.minutes': '\$0 min',
  'auto.hours': '\$0 h',
  'auto.days': '\$0 d',
  'auto.lastRun': 'Last run \$0',
  'auto.err.title': 'Title is required',
  'auto.err.prompt': 'Instruction is required',
  'auto.err.cron': 'Cron expression is required',
  'auto.err.interval': 'Interval must be a positive integer',
  'auto.err.delay': 'Delay must be between 1 minute and 1 year',
  'tasks.menu.offPeak': 'Off-peak tasks',
  'op.title': 'Off-peak tasks',
  'op.subtitle': 'Free runs in compute-rich windows · Coding Plan',
  'op.hint':
      'Queued after submitting, executed free in compute-rich windows; requires a Coding Plan subscription',
  'op.add': 'New off-peak task',
  'op.submit': 'Create idle-time task',
  'op.empty':
      'No idle-time tasks yet. Create one to run free when compute is idle.',
  'op.loading': 'Loading off-peak tasks…',
  'op.loadFailed': 'Load failed: \$0',
  'op.unavailable.title': 'Off-peak tasks unavailable',
  'op.unavailable.body':
      'The device is offline or the protocol handshake is unfinished; try again later.',
  'op.name': 'Task title',
  'op.name.hint': 'e.g. Nightly refactor',
  'op.prompt': 'Instructions',
  'op.prompt.hint':
      'Describe a task ZCode can work on in the background, including the expected result and any constraints…',
  'op.model': 'Model',
  'op.earliestAt': 'Soonest available',
  'op.earliest.any': 'Any — run as soon as queued',
  'op.keepAwake': 'Keep awake',
  'op.keepAwakeHint':
      'Keep the device connection alive so results arrive promptly',
  'op.permission': 'Permission mode',
  'op.permission.build': 'Confirm changes',
  'op.permission.plan': 'Plan mode',
  'op.permission.yolo': 'Full access',
  'op.permissionWarning':
      'Idle-time runs are unattended. Actions that need confirmation will pause the task until you respond.',
  'op.fullAccessHint':
      'Switch permissions to Full access to reduce task failures',
  'op.tpl.ci.title': 'CI failures & flaky tests report',
  'op.tpl.ci.prompt':
      'Scan recent CI runs, list failing and flaky tests with likely causes, and suggest fixes ordered by impact.',
  'op.tpl.docs.title': 'Documentation sync check',
  'op.tpl.docs.prompt':
      'Based on the current code and recent commits, check whether README, docs, config guides and usage examples are outdated or inconsistent. Only change what can be confirmed directly from code, config or commit history; do not guess unverified behavior; keep the existing structure, terminology and style. List changed files with the rationale for each; if nothing changed, state the scope, evidence and conclusion.',
  'op.tpl.standup.title': 'Git standup summary',
  'op.tpl.standup.prompt':
      'Summarize this week\'s Git activity into a Friday standup: notable commits, merged PRs and main changes, kept concise.',
  'op.created': 'Off-peak task submitted',
  'op.quota': '\$0 quota left',
  'op.earliest': 'Earliest \$0',
  'op.minutes': '\$0 min',
  'op.hours': '\$0 h',
  'op.duration': 'Took \$0',
  'op.queue': 'Queue position \$0',
  'op.status.queued': 'Waiting for idle capacity',
  'op.status.running': 'Running',
  'op.status.paused': 'Paused',
  'op.status.completed': 'Completed',
  'op.status.failed': 'Failed',
  'op.status.cancelled': 'Cancelled',
  'op.viewResult': 'Open session',
  'op.cancel': 'Cancel task',
  'op.cancel.title': 'Cancel this idle-time task?',
  'op.cancel.body': '"\$0" will stop; files already modified are kept.',
  'op.cancel.confirm': 'Cancel task',
  'op.deleteTitle': 'Delete this idle-time task?',
  'op.deleteBody':
      'This cannot be undone. A queued or running task stops immediately.',
  'op.delete.confirm': 'Delete idle-time task',
  'op.section.active': 'Active',
  'op.section.history': 'History',
  'op.err.prompt': 'Instruction is required',
  'op.err.noWorkspace': 'No open workspace on this device',
  'op.err.codingPlanOnly': 'Off-peak tasks require a Coding Plan subscription',
  'op.err.quota': 'Monthly off-peak quota is used up',
  'op.err.unavailable': 'Off-peak service is temporarily unavailable',
  'op.err.other': 'Operation failed: \$0',
  'settings.notifications': 'Notifications',
  'settings.notificationsHint':
      'Task completions, off-peak results and automation runs pushed locally',
  'settings.notify.tasks': 'Task events',
  'settings.notify.offPeak': 'Off-peak events',
  'settings.notify.auto': 'Automation results',
  'notify.task.done': 'Task completed',
  'notify.task.failed': 'Task failed',
  'notify.task.interrupted': 'Task interrupted',
  'notify.offPeak.done': 'Off-peak task completed',
  'notify.offPeak.failed': 'Off-peak task failed',
  'notify.auto.done': 'Automation triggered',
  'notify.auto.failed': 'Automation run failed',
  'settings.checkUpdate': 'Check for updates',
  'update.latest': 'Up to date',
  'update.newVersion': 'New version v\$0',
  'update.availableBody': 'A new ZLinker version is available.',
  'update.download': 'Download in browser',
  'update.later': 'Later',
  'update.failed': 'Update check failed: \$0',
  'update.storePending': 'Check for updates in the App Store',

  // ---- Off-peak functional alignment (official desktop dictionary) ----
  'op.tab.settings': 'Settings',
  'op.tab.history': 'History',
  'op.history.empty': 'No history yet.',
  'op.history.delete': 'Delete history',
  'op.badge.paused': '#\$0 Paused',
  'op.pauseHint':
      'Tasks paused beyond the queue wait time will be placed back in the queue',
  'op.continueHint':
      'If the queue ticket has expired, Continue re-queues the task at the back.',
  'op.discard.title': 'Discard Idle-time task draft?',
  'op.discard.body': 'Your changes to the current idle-time task will be lost.',
  'op.discard.confirm': 'Discard',
  'op.banner':
      'New feature for subscribers: Create "Idle-time task", We will complete your assigned task for free during periods of surplus computing power.',
  'op.edit': 'Edit Idle-time task',
  'op.edit.hint':
      'Update the instructions and how this task runs during idle time.',
  'op.edit.save': 'Save',
  'op.edit.menu': 'Edit',
  'op.peakWarning':
      'This task runs during peak hours, which may cause errors to occur.',
  'op.limitReachedAt':
      'Free tier limit reached. You can create another task in \$0.',
  'op.thought': 'Thinking',
  'op.thought.default': 'Default (unspecified)',
  'op.remaining.min': '\$0 min',
  'op.remaining.hoursMin': '\$0 hr \$1 min',

  // ---- Automations functional alignment (official desktop dictionary) ----
  'auto.preset': 'Frequency',
  'auto.freq.hourly': 'Hourly',
  'auto.freq.daily': 'Daily',
  'auto.freq.weekdays': 'Weekdays',
  'auto.freq.weekly': 'Weekly',
  'auto.freq.monthly': 'Monthly',
  'auto.freq.customInterval': 'Custom…',
  'auto.time': 'Time',
  'auto.weekdayPick': 'Pick weekdays',
  'auto.monthDay': 'Day of month',
  'auto.custom.title': 'Custom repeat',
  'auto.custom.everyN': 'Every \$0 \$1',
  'auto.custom.ends': 'Ends',
  'auto.custom.never': 'Never ends',
  'auto.custom.until': 'On date',
  'auto.custom.dateLabel': 'Pick end date',
  'auto.custom.estRuns': 'Stops after about \$0 runs',
  'auto.schedule.preview': 'Runs: \$0',
  'auto.nextRun': 'Next run \$0',
  'auto.runCount': 'Ran \$0 times',
  'auto.runCountLimited': 'Ran \$0/\$1 times',
  'auto.runNow': 'Run now',
  'auto.runNowQueued': 'Triggered — starting soon',
  'auto.runNowDuplicate': 'A run is already in progress — try again later',
  'auto.runNowFailed': 'Failed to trigger a run',
  'auto.templates': 'Task templates',
  'auto.tpl.pick': 'Use template',
  'auto.tpl.weeklyReview.title': 'Weekly review',
  'auto.tpl.weeklyReview.desc': 'A Friday summary of what happened this week.',
  'auto.tpl.weeklyReview.prompt':
      'Create a concise Friday review from verifiable activity in this project. Summarize what changed, open follow-ups, and unavailable evidence without modifying code or external state.',
  'auto.tpl.weeklyReview.schedule': 'Every Friday at 16:00',
  'auto.tpl.meetingPrep.title': 'Meeting prep',
  'auto.tpl.meetingPrep.desc': 'A Friday summary of what happened this week.',
  'auto.tpl.meetingPrep.prompt':
      'Prepare a concise meeting brief from available calendar and project evidence. Cover attendees, context, and agenda; label unavailable information and do not modify external state.',
  'auto.tpl.meetingPrep.schedule': 'Every Friday at 16:00',
  'auto.tpl.contentIdeas.title': 'Content ideas',
  'auto.tpl.contentIdeas.desc':
      'Draft a few post ideas each week from the latest news in your industry.',
  'auto.tpl.contentIdeas.prompt':
      'Draft a few content ideas from verifiable recent industry and project information. Cite the evidence used, label unavailable information, and do not publish or modify external state.',
  'auto.tpl.contentIdeas.schedule': 'Every Monday at 9:00',
};
